aquasecurity/trivy-operator

docs/index.md
=> docs(operator): remove cli ref

deploy/crd/ciskubebenchreports.crd.yaml, deploy/crd/clustercompliancedetailreports.crd.yaml, deploy/crd/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/clustervulnerabilityreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/kubehunterreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/trivy-operator.yaml, mkdocs.yml
=> release(operator): release prepare v0.0.2

deploy/helm/values.yaml
=> chore(helm): fix lint issue

deploy/crd/ciskubebenchreports.crd.yaml, deploy/crd/clustercompliancedetailreports.crd.yaml, deploy/crd/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/clustervulnerabilityreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/kubehunterreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/trivy-operator.yaml, mkdocs.yml
=> release(operator): release prepare v0.0.3

README.md
=> docs: remove kube hunter ref

README.md
=> docs(main): update-docker-pull-badge

Makefile, misc/triage/labels.yaml
Treat labels as code.
- Close https://github.com/aquasecurity/trivy-operator/issues/74
=> chore: add labels.yaml

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
- Close https://github.com/aquasecurity/trivy-operator/issues/73
=> chore: update github issue template

deploy/crd/ciskubebenchreports.crd.yaml, deploy/crd/clustercompliancedetailreports.crd.yaml, deploy/crd/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/clustervulnerabilityreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, mkdocs.yml
Release prepare v0.0.4
- Close #89
=> release(operator): release prepare v0.0.4

deploy/helm/values.yaml
=> chore: chore/remove-chart-trailing-spaces

deploy/crd/ciskubebenchreports.crd.yaml, deploy/crd/clustercompliancedetailreports.crd.yaml, deploy/crd/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/clustervulnerabilityreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, mkdocs.yml
=> release(operator): release prepare v0.0.5

README.md
=> docs: update main doc broken links

.github/ISSUE_TEMPLATE/bug_report.md
=> fix: add label to bug issue template

.github/workflows/build.yaml
=> fix: remove compliance crd from itests

deploy/helm/values.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/trivy-operator.yaml, docs/vulnerability-scanning/trivy.md, itest/matcher/matcher.go, itest/matcher/matcher_test.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go
- Close https://github.com/aquasecurity/trivy-operator/issues/104
=> chore: update trivy to 0.28.1

deploy/compliance/clustercompliancedetailreports.crd.yaml, deploy/compliance/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, mkdocs.yml
=> release(operator): release prepare 0.0.6

deploy/compliance/clustercompliancedetailreports.crd.yaml, deploy/compliance/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, mkdocs.yml
=> release(operator): release prepare 0.0.7

mkdocs.yml
=> docs: remove black lines mkdocs

pkg/kube/secrets.go, pkg/kube/secrets_test.go
Support  ImagePullSecret server discovery with wildcard
- Close #148 
=> fix: ImagePullSecret server discovery with wildcard

docs/crds/vulnerability-report.md
Updating docs for https://github.com/aquasecurity/trivy-operator/pull/147
=> docs: update vulnerability-report.md

deploy/helm/values.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/trivy-operator.yaml, docs/crds/vulnerability-report.md, docs/vulnerability-scanning/trivy.md, itest/matcher/matcher.go, itest/matcher/matcher_test.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go
=> update trivy to 0.29.1

docs/vulnerability-scanning/managed-registries.md
=> docs: fix config validation

pkg/plugin/trivy/plugin.go
Added ECR-Region support as already done and working on old deprecated `starboard-operator`
Reference: https://github.com/aquasecurity/starboard/pull/1191/
=> Added Region support for ECR-Registry handling.

pkg/metrics/collector.go, pkg/metrics/collector_test.go
Related to https://github.com/aquasecurity/trivy-operator/issues/78
=> feat: add exposedsecrets metrics

docs/integrations/metrics.md, mkdocs.yml
Related https://github.com/aquasecurity/trivy-operator/issues/78
=> docs: add integration/metrics

deploy/compliance/clustercompliancedetailreports.crd.yaml, deploy/compliance/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/exposedsecretreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, mkdocs.yml
=> release: prepate release v0.1.0-rc

deploy/helm/values.yaml
Fix helm lint -> https://github.com/aquasecurity/trivy-operator/runs/7119412781?check_suite_focus=true
=> lint: fix helm chart

deploy/compliance/clustercompliancedetailreports.crd.yaml, deploy/compliance/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/exposedsecretreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, mkdocs.yml
=> release: prepare release v0.1.0-rc-2

deploy/compliance/clustercompliancedetailreports.crd.yaml, deploy/compliance/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/exposedsecretreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, mkdocs.yml
=> relase: prepare 0.1.0

RELEASING.md
=> docs: fix RELEASING.md

deploy/helm/templates/deployment.yaml, deploy/helm/templates/service.yaml, deploy/helm/templates/servicemonitor.yaml, deploy/helm/values.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/06-trivy-operator.service.yaml, deploy/static/trivy-operator.yaml, hack/update-static.yaml.sh
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
- Close #194
PTAL @eminaktas
=> Add ServiceMonitor to Helm

deploy/static/06-trivy-operator.service.yaml, deploy/static/trivy-operator.yaml
Follow up to https://github.com/aquasecurity/trivy-operator/pull/195
=> fix: deploy/static

Makefile, go.mod, go.sum, hack/tools.go, itest/trivy-operator/behavior/behavior.go, itest/trivy-operator/starboard_operator_test.go, itest/trivy-operator/suite_test.go, pkg/compliance/clustercompliancereport_test.go, pkg/compliance/compliance_suite_test.go, pkg/metrics/collector_test.go, pkg/metrics/metrics_suite_test.go, pkg/operator/controller/controller_suite_test.go, pkg/operator/controller/limit_checker_test.go, pkg/operator/predicate/predicate_suite_test.go, pkg/operator/predicate/predicate_test.go
Upgrades Ginkgo to the new major version, which has been out for while...
=> chore: upgrade to Ginkgo v2

.github/workflows/release.yaml, .goreleaser.yaml
deploy images to ecr public repository
- Close #250 
=> chore: deploy images to ecr public repository

pkg/rbacassessment/doc.go
fix: update rbac assessment doc
=> fix: update rbac assessment doc

pkg/apis/aquasecurity/v1alpha1/compliance_types.go, pkg/apis/aquasecurity/v1alpha1/config_audit_types.go, pkg/apis/aquasecurity/v1alpha1/exposed_secrets_types.go, pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go
=> chore: delete unused consts

pkg/configauditreport/controller/controller.go
reduce code duplication in reconcile configMap
=> fix: report item closure

pkg/metrics/collector.go, pkg/metrics/collector_test.go
rbac assessment metrics
- Close #248 
=> feat: rbac assessment metrics

deploy/compliance/aquasecurity.github.io_clustercompliancedetailreports.yaml, deploy/compliance/aquasecurity.github.io_clustercompliancereports.yaml, deploy/crd/aquasecurity.github.io_clusterconfigauditreports.yaml, deploy/crd/aquasecurity.github.io_clusterrbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_configauditreports.yaml, deploy/crd/aquasecurity.github.io_exposedsecretreports.yaml, deploy/crd/aquasecurity.github.io_rbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_vulnerabilityreports.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/06-trivy-operator.service.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
=> release: prepare release v0.1.1

deploy/compliance/aquasecurity.github.io_clustercompliancedetailreports.yaml, deploy/compliance/aquasecurity.github.io_clustercompliancereports.yaml, deploy/crd/aquasecurity.github.io_clusterconfigauditreports.yaml, deploy/crd/aquasecurity.github.io_clusterrbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_configauditreports.yaml, deploy/crd/aquasecurity.github.io_exposedsecretreports.yaml, deploy/crd/aquasecurity.github.io_rbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_vulnerabilityreports.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/06-trivy-operator.service.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
=> release: prepare release v0.1.2

.goreleaser.yaml
=> chore: add ecr ubi8 amd64 image

deploy/compliance/aquasecurity.github.io_clustercompliancedetailreports.yaml, deploy/compliance/aquasecurity.github.io_clustercompliancereports.yaml, deploy/crd/aquasecurity.github.io_clusterconfigauditreports.yaml, deploy/crd/aquasecurity.github.io_clusterrbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_configauditreports.yaml, deploy/crd/aquasecurity.github.io_exposedsecretreports.yaml, deploy/crd/aquasecurity.github.io_rbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_vulnerabilityreports.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/06-trivy-operator.service.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
=> release: prepare release v0.1.3-rc

deploy/helm/templates/rbac.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml
add permission to rbacassessmentreports and clusterrbacassessmentreports
=> chore: add permission to rbacassessmentreports

deploy/compliance/aquasecurity.github.io_clustercompliancedetailreports.yaml, deploy/compliance/aquasecurity.github.io_clustercompliancereports.yaml, deploy/crd/aquasecurity.github.io_clusterconfigauditreports.yaml, deploy/crd/aquasecurity.github.io_clusterrbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_configauditreports.yaml, deploy/crd/aquasecurity.github.io_exposedsecretreports.yaml, deploy/crd/aquasecurity.github.io_rbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_vulnerabilityreports.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/06-trivy-operator.service.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
=> release: prepare release v0.1.3-rc.2

deploy/compliance/aquasecurity.github.io_clustercompliancedetailreports.yaml, deploy/compliance/aquasecurity.github.io_clustercompliancereports.yaml, deploy/crd/aquasecurity.github.io_clusterconfigauditreports.yaml, deploy/crd/aquasecurity.github.io_clusterrbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_configauditreports.yaml, deploy/crd/aquasecurity.github.io_exposedsecretreports.yaml, deploy/crd/aquasecurity.github.io_rbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_vulnerabilityreports.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-trivy-operator.ns.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/04-trivy-operator.policies.yaml, deploy/static/05-trivy-operator.deployment.yaml, deploy/static/06-trivy-operator.service.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
=> release: prepare release v0.1.3

itest/helper/helper.go, pkg/apis/aquasecurity/v1alpha1/common_types.go, pkg/apis/aquasecurity/v1alpha1/compliancedetail_types.go, pkg/apis/aquasecurity/v1alpha1/register.go, pkg/kube/object.go, pkg/operator/predicate/predicate.go, pkg/trivyoperator/constants.go, pkg/vulnerabilityreport/builder.go
=> chore: delete dead code

pkg/kube/secrets.go
This is a follow-up after reviewing https://github.com/aquasecurity/trivy-operator/pull/270, as I found the conditional in `imagePullSecretDefineAndNoSecretsFound` hard to read and understand. I also question the logic here, but that we can decide on later.
=> refactor: make code to read image pull secrets more readable

mkdocs.yml
add rbac assessment crd md ref
- Close #302
=> docs: add rbac assessment crd md ref

pkg/kube/secrets.go, pkg/kube/secrets_test.go
=> chore: dead code cleanup

deploy/helm/generated/role.yaml, deploy/static/trivy-operator.yaml, go.mod, go.sum, itest/trivy-operator/behavior/behavior.go, pkg/configauditreport/controller/controller.go, pkg/configauditreport/io.go, pkg/configauditreport/io_test.go, pkg/exposedsecretreport/io.go, pkg/exposedsecretreport/io_test.go, pkg/kube/object.go, pkg/kube/object_test.go, pkg/operator/operator.go, pkg/plugin/factory.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go, pkg/rbacassessment/io.go, pkg/rbacassessment/io_test.go, pkg/trivyoperator/config.go, pkg/vulnerabilityreport/controller.go, pkg/vulnerabilityreport/io.go, pkg/vulnerabilityreport/io_test.go
=> Prepare k8s 1.25 support

deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, docs/crds/exposedsecret-report.md, docs/crds/vulnerability-report.md, docs/vulnerability-scanning/trivy.md, itest/matcher/matcher.go, itest/matcher/matcher_test.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
=> chore: bump trivy version 0.30.0

pkg/vulnerabilityreport/ttl_report.go, pkg/vulnerabilityreport/ttl_report_test.go
Before making changes to the TTLReportReconciler, unit test the functionality
- related #237
=> Unit test TTLReportReconciler controller

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
prepare release v0.1.4
- [x ] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
=> release: prepare release v0.1.4-rc

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
=> release: prepare release v0.1.4

pkg/configauditreport/controller/controller.go
=> chore: lint issues in assignment

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
=> release: prepare v0.1.5-rc

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
=> release: prepare v0.1.5

deploy/helm/values.yaml, pkg/vulnerabilityreport/controller.go
What we currently do is that we fetch the stream, but when error occurs while unmarshalling we can't close the log reader stream, which stays in memory while gc finds and deletes it. As an idea was to extract the logic to standalone function which does the fetching of log buffer and defers on closing it.
=> Extraction of log reading logic to defer its close

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
Prepare release v0.1.6-rc  
Depend on #424
=> release: prepare release v0.1.6-rc

deploy/helm/values.yaml
=> chore: space in helm comment lint

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
release: prepare release 0.1.7-rc
=> release: prepare release 0.1.7-rc

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
=> release: version 0.1.7

pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/vulnerabilityreport/testdata/fixture/cronjob-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/daemonset-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/job-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/pod-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/replicaset-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/replicationcontroller-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/statefulset-expected-scan.yaml
- Close https://github.com/aquasecurity/trivy-operator/issues/449
=> fix: fixing trivy security-checks

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
release: prepare release 0.1.8-rc
=> release: prepare release 0.1.8-rc

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
=> release: version 0.1.8

pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/vulnerabilityreport/testdata/fixture/cronjob-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/daemonset-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/job-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/pod-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/replicaset-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/replicationcontroller-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/statefulset-expected-scan.yaml
=> fix: scan mount is not unique

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, mkdocs.yml
=> release: prepare v0.1.9-rc

go.mod, go.sum, pkg/configauditreport/controller/controller.go, pkg/policy/policy.go, pkg/policy/policy_test.go, pkg/policy/testdata/fixture/buitin_result.json
update defsec lib version
- Close #455
=> chore: update defsec lib version

pkg/configauditreport/controller/controller.go, pkg/operator/workload/helper.go, pkg/vulnerabilityreport/controller.go
=> refactor: reuse controllers code

pkg/configauditreport/controller/controller.go
Ignore infra components checks
Relates #455
=> fix: ignore infra components checks

pkg/compliance/io_test.go, pkg/policy/policy_test.go
minor fix to avoid noisy tests
=> refactor: remove println

deploy/helm/generated/role.yaml, deploy/static/trivy-operator.yaml, pkg/vulnerabilityreport/controller.go
return back update secret verb to Cluster Role
- Close #492
=> chore: return update secret verb to Role

deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml
configure operator automountServiceAccountToken
- Related #402 
=> chore: configure operator automountServiceAccountToken

docs/tutorials/private-registries.md, mkdocs.yml
Adding tutorial on accessing container images from a private registry.
=> Docs: Private registry tutorial

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.2.0-rc

deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, docs/crds/exposedsecret-report.md, docs/crds/vulnerability-report.md, docs/vulnerability-scanning/trivy.md, itest/matcher/matcher.go, itest/matcher/matcher_test.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
update trivy to v0.31.3
- Close #513
=> chore: update trivy to 0.31.3

.github/workflows/build.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/release.yaml, .golangci.yml, CONTRIBUTING.md, go.mod, pkg/apis/aquasecurity/v1alpha1/compliance_types.go, pkg/compliance/clustercompliancereport_test.go, pkg/compliance/io.go, pkg/compliance/io_test.go, pkg/compliance/mapper_test.go, pkg/kube/object.go, pkg/kube/secrets_test.go, pkg/plugins/trivy/plugin.go, pkg/policy/policy.go, pkg/policy/policy_test.go, pkg/trivyoperator/config_test.go, pkg/utils/compressutil.go, pkg/utils/compressutil_test.go, pkg/utils/dateutil.go, pkg/utils/util.go, pkg/vulnerabilityreport/suite_test.go, pkg/vulnerabilityreport/ttl_report.go, pkg/vulnerabilityreport/ttl_report_test.go
bump go-version 1.19.1
- Close #516
=> chore:bump go-version 1.19

go.mod, go.sum, pkg/configauditreport/controller/controller.go, pkg/policy/testdata/fixture/buitin_result.json
bump-defsec-v0.75.3
- Close #407 
- Close #391
=> chore: bump-defsec-v0.75.3

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.2.0-rc3

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.2.0

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.2.1

pkg/policy/policy.go
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
- Close #526 
=> feat: add namespace for external policies

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.3.0-rc

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.3.0

deploy/helm/Chart.yaml, deploy/helm/values.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.4.0-rc

docs/tutorials/microk8s.md, mkdocs.yml
I have detailed how to use the microk8s addon in a separate tutorial.
=> Docs: adding a microk8s tutorial to the tutorials section

pkg/metrics/collector.go, pkg/metrics/collector_test.go, pkg/metrics/types.go, pkg/metrics/types_test.go
Hi, i add a nnew type to manage Severity labels on metrics modules. It will fix case divergences identify in #568.
I have separate metrics process for `trivy_image_vulnerabilities` and `trivy_vulnerability_id`metrics in 2 different functions.
I have add somes unit tests on theses new metrics. 
- Close #568
=> feat: use same labels value case

go.mod, go.sum, pkg/policy/policy_test.go
update defsec lib to version v0.78.0
=> chore: update defsec lib

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.4.0-rc2

pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/utils/compressutil.go, pkg/utils/compressutil_test.go
fs system scanning uncompressed report
- Close #592
=> fix: fs system scanning uncompressed report

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=>  release: prepare v0.4.0-rc3

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.4.0

docs/configuration-auditing/built-in-policies.md
docs: add rbac policies
- Close #602
=> docs: add rbac policies

.github/workflows/release-snapshot.yaml
Add team notification for security issues found on `trivy-operator` image
=> chore: add teams notification

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
release: prepare release v0.5.0-rc
=> release: prepare release v0.5.0-rc

docs/integrations/metrics.md
Add details on metrics data
- Close #225
=> docs: metrics

docs/vulnerability-scanning/managed-registries.md
Add documentation for managed registries gcr
=> docs: managed registries gcr

deploy/helm/Chart.yaml, deploy/helm/values.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.6.0-rc2

docs/integrations/metrics.md
=> docs: update metrics page

pkg/configauditreport/controller/controller.go, pkg/operator/operator.go
Remove ingress resource from reconciling
=> fix: remove ingress resource from reconciling

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare-v0.6.0

pkg/trivyoperator/config.go
Refactor variable name to camel case
=> refactor: variable name to camel case

deploy/helm/values.yaml
=> chore: chart-lint-trailing-spaces

pkg/configauditreport/controller/controller.go
Infra assessment report should include only k8s core components
- Close #709
=> fix: filter k8s core components

.github/workflows/stale-issues.yaml
=> chore: add stale bot

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=>  release: prepare v0.7.0-rc2

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.7.0

deploy/helm/Chart.yaml, mkdocs.yml
=> release: chart-v0.7.1

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare-v0.7.1

pkg/operator/ttl_report.go
add infra assessment ttl support
- Close #721
=> fix: add infra assessment ttl

deploy/helm/templates/trivy-server.yaml
configure trivy server image repository and tag
- Close #729
=> chore: configure trivy server image repository and tag

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.8.0-rc

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.8.0-rc2

deploy/helm/README.md
add helm readme 
- Related #665
=> docs: add helm readme

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.8.0 rc3

README.md
docs: add artifacthub badge
- Related #665
=> docs: add artifacthub badge

pkg/vulnerabilityreport/controller/trivyserver.go
=> chore: format

deploy/helm/Chart.yaml, deploy/helm/values.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml, pkg/plugins/trivy/plugin_test.go
=> release: prepare-v0.9.0-rc

pkg/operator/envtest/controller_test.go, pkg/operator/envtest/suite_test.go, pkg/operator/envtest/testdata/fixture/api-server-infraassessmentreport-expected.yaml, pkg/operator/envtest/testdata/fixture/api-server.yaml
=> test: add infra assessment itests

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/crds/configaudit-report.md, docs/crds/exposedsecret-report.md, docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.9.0-rc2

deploy/helm/templates/config.yaml, deploy/helm/values.yaml
expose skipDirs helm param 
- Close #676
=> chore: expose skip-dir helm param

.github/workflows/build.yaml, .github/workflows/publish-docs.yaml, .github/workflows/publish-helm-chart.yaml
bump actions/setup-python from 4.3.0 to 4.3.1
=> chore: bump actions/setup-python from 4.3.0 to 4.3.1

pkg/kube/object.go
fix wrong labels scan-job (cronjob)
- Close #509
=> fix: wrong labels scan-job

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare-v0.10.0-rc

pkg/kube/object.go
wrong labels scan-job update 
- Related #509
=> fix: wrong labels scan-job update

deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.10.0-rc2

pkg/plugins/trivy/plugin.go
Add protection when links are empty
- Close #792
=> feat: add protection when links are empty

deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, docs/docs/crds/clustercompliance-report.md, go.mod, go.sum, pkg/compliance/io.go, pkg/compliance/io_test.go, pkg/operator/envtest/testdata/fixture/compliance-detail-status-expected.yaml, pkg/operator/envtest/testdata/fixture/compliance-detail.yaml, pkg/operator/envtest/testdata/fixture/compliance-summary-status-expected.yaml, pkg/operator/envtest/testdata/fixture/compliance-summary.yaml, pkg/operator/envtest/testdata/fixture/cronjob-configauditreport-expected.yaml, pkg/operator/envtest/testdata/fixture/daemonset-configauditreport-expected.yaml, pkg/operator/envtest/testdata/fixture/job-configauditreport-expected.yaml, pkg/operator/envtest/testdata/fixture/pod-configauditreport-expected.yaml, pkg/operator/envtest/testdata/fixture/replicaset-configauditreport-expected.yaml
Add cis benchmark report
- Close #814
- [ x I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
=> feat: add cis benchmark report

deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml
support volume mount
- Close #698 
=> chore: support volume mount

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.10.0-rc3

deploy/helm/values.yaml
=> chore: fix chart lint issues

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.10.0-rc4

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.10.0

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare release v0.10.1

.github/workflows/e2e.yaml, tests/e2e/workload-image/00-trivy-operator-image.yaml
=> test: workload e2e test

.github/workflows/e2e.yaml, goreleaser-e2e.yaml, tests/e2e/config/kuttl.yaml, tests/e2e/workload-image/00-trivy-operator-image.yaml
=> test: workload e2e

README.md
=> docs: e2e badge

README.md
=> docs: e2e badge typo

.github/workflows/e2e.yaml
=> test: config file location

.github/workflows/e2e.yaml, tests/config/client-server.yaml, tests/e2e/client-server/manifests/trivy-operator-client-server.yaml, tests/e2e/client-server/workload/00-assert.yaml, tests/e2e/client-server/workload/00-install-pod.yaml, tests/resources-cleanup.sh
=> test: client-server mode

tests/config/client-server.yaml, tests/config/fs-mode.yaml, tests/config/image-mode.yaml
=> chore: e2e test steps timeout

tests/config/client-server.yaml, tests/config/fs-mode.yaml, tests/config/image-mode.yaml, tests/e2e/client-server/manifests/trivy-operator-client-server.yaml, tests/e2e/fs-mode/manifests/trivy-operator-fs.yaml
=> chore: e2e image repo

.gitignore, tests/e2e/client-server/manifests/trivy-operator-client-server.yaml, tests/e2e/client-server/workload/00-assert.yaml, tests/e2e/client-server/workload/00-pod.yaml, tests/e2e/client-server/workload/01-assert.yaml, tests/e2e/client-server/workload/02-assert.yaml, tests/e2e/client-server/workload/03-assert.yaml, tests/e2e/fs-mode/manifests/trivy-operator-fs.yaml, tests/e2e/fs-mode/workload/00-assert.yaml, tests/e2e/fs-mode/workload/00-pod.yaml, tests/e2e/fs-mode/workload/01-assert.yaml, tests/e2e/fs-mode/workload/02-assert.yaml, tests/e2e/fs-mode/workload/03-assert.yaml, tests/e2e/image-mode/workload/00-assert.yaml, tests/e2e/image-mode/workload/00-pod.yaml, tests/e2e/image-mode/workload/01-assert.yaml, tests/e2e/image-mode/workload/02-assert.yaml, tests/e2e/image-mode/workload/03-assert.yaml
=> test: config-audit assert

.github/workflows/e2e.yaml, goreleaser-e2e.yaml, tests/e2e/client-server/manifests/trivy-operator-client-server.yaml, tests/e2e/fs-mode/manifests/trivy-operator-fs.yaml, tests/e2e/image-mode/manifests/trivy-operator-image.yaml
=> chore: update image repo to ghcr

.github/workflows/e2e.yaml, tests/e2e/client-server/manifests/trivy-operator-client-server.yaml, tests/e2e/fs-mode/manifests/trivy-operator-fs.yaml, tests/e2e/image-mode/manifests/trivy-operator-image.yaml
=> chore: replace e2e tag with snapshot

Makefile, pkg/operator/envtest/controller_test.go
=> test: increase test timeout

deploy/helm/Chart.yaml, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.10.2

tests/e2e/client-server/manifests/trivy-operator-client-server.yaml, tests/e2e/fs-mode/manifests/trivy-operator-fs.yaml, tests/e2e/image-mode/manifests/trivy-operator-image.yaml
=> test: e2e exclude namespaces

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/e2e/client-server/manifests/trivy-operator-client-server.yaml, tests/e2e/fs-mode/manifests/trivy-operator-fs.yaml, tests/e2e/image-mode/manifests/trivy-operator-image.yaml
=> release: prepare v0.11.0-rc2

README.md
=> docs: update compliance report

itest/trivy-operator/starboard_operator_test.go, pkg/apis/aquasecurity/v1alpha1/compliance_types.go, pkg/compliance/io.go
Signed-off-by: fengshunli <1171313930@qq.com>
Update comment formatting
=> fix: comment formatting

pkg/configauditreport/controller/helper.go, pkg/configauditreport/controller/resource.go, pkg/operator/operator.go, pkg/operator/ttl_report.go
disable infra assessment report buy config
- Close #911
=> fix: disable infra assessment report

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/e2e/client-server/manifests/trivy-operator-client-server.yaml, tests/e2e/fs-mode/manifests/trivy-operator-fs.yaml, tests/e2e/image-mode/manifests/trivy-operator-image.yaml
=> release: prepare v0.11.0-rc3

.github/workflows/e2e.yaml, tests/config/node-collector.yaml, tests/e2e/node-collector/node/00-assert.yaml, tests/e2e/node-collector/node/00-trivy-operator.yaml, tests/e2e/node-collector/node/01-assert.yaml
End 2 end test for node collector producing cluster infra assessment report
- Close #914
=> test: node collector producing cluster infra assessment reoprt

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/e2e/client-server/manifests/trivy-operator.yaml, tests/e2e/fs-mode/manifests/trivy-operator.yaml, tests/e2e/image-mode/manifests/trivy-operator.yaml
=> release: prepare  v0.11.0

deploy/helm/Chart.yaml, deploy/helm/values.yaml
=> chore: lint helm

deploy/helm/Chart.yaml
=> chore: helm ver revert

.github/workflows/build.yaml
=> chore: helm-lint-pipeline

go.mod, go.sum, pkg/configauditreport/controller/node.go
update node collector job template
- Close #935
=> fix: update node collector job template

build/trivy-operator/Dockerfile
alpine security CVE-2023-0286
- Close #933
=> fix: alpine security CVE-2023-0286

pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, tests/config/client-server.yaml
fix cache for java db cache 
- Close #948
=> fix: java db cache

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/e2e/client-server/manifests/trivy-operator.yaml, tests/e2e/fs-mode/manifests/trivy-operator.yaml, tests/e2e/image-mode/manifests/trivy-operator.yaml
=> release: prepare v0.11.1-rc

.github/workflows/build.yaml
Add e2e test to build workflow
=> chore: add e2e build workflow

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.11.1

pkg/configauditreport/controller/resource.go, pkg/docker/config.go, pkg/operator/envtest/controller_test.go, pkg/operator/envtest/suite_test.go, pkg/operator/operator.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/policy/policy.go
Signed-off-by: fengshunli <1171313930@qq.com>
Code format and lint fixes
- Close #952
=> fix: code format

.github/workflows/build.yaml, Makefile, pkg/operator/envtest/suite_test.go
separate envtest on build workflow
- Close #968
=> chore: separate envtest workflow

pkg/operator/envtest/controller_test.go, pkg/operator/envtest/testdata/fixture/config-audit-ttl-historical.yaml, pkg/operator/envtest/testdata/fixture/config-audit-ttl.yaml
Fix Envtest ttl misconfig flaky test
=> test: ttl misconfig flaky test

pkg/configauditreport/controller/helper.go, pkg/configauditreport/plugin.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/policy/policy.go, pkg/policy/policy_test.go
https://github.com/aquasecurity/trivy-operator/issues/849#event-8498354536
- Close #849
=> fix: get the data of the specified severity

README.md
=> docs: remove e2e badge

CONTRIBUTING.md
Contribution guide update envtest / end 2 end tests
=> docs: contribution guide update

go.mod, go.sum
=> build(deps): Bump golang.org/x/net from 0.6.0 to 0.7.0

.github/workflows/build.yaml, .github/workflows/chart-testing.yaml, .github/workflows/publish-docs.yaml, .github/workflows/publish-helm-chart.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/release.yaml
update runs-on:  image to `latest`
- Close #991
=> chore:: update ubuntu-20.04 to ubuntu-latest

README.md, deploy/specs/pss-baseline.yaml, deploy/specs/pss-restricted.yaml, docs/docs/compliance/compliance.md
Add pss compliance reports
- Close #986
=> feat: support pss compliance reports

.github/workflows/build.yaml, .github/workflows/chart-testing.yaml, .github/workflows/publish-helm-chart.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/release.yaml
unified env format and update kind version v0.17.0
=> fix: ci format

docs/tutorials/integrations/webhook.md, pkg/webhook/webhookreporter.go
extend webhook support misconfig/rbac and infra assessment
- Close #918
=> feat: webhook support misconfig

.github/workflows/build.yaml, tests/e2e/client-server/workload/01-exposedsecret.yaml, tests/e2e/client-server/workload/04-assert.yaml, tests/e2e/client-server/workload/05-assert.yaml, tests/e2e/fs-mode/workload/01-exposedsecret.yaml, tests/e2e/fs-mode/workload/04-assert.yaml, tests/e2e/fs-mode/workload/05-assert.yaml, tests/e2e/image-mode/workload/01-exposedsecret.yaml, tests/e2e/image-mode/workload/04-assert.yaml, tests/e2e/image-mode/workload/05-assert.yaml
Add coverage for exposed secret e2e test
- Close #1003
=> test: exposed secrets e2e

deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
bump trivy 0.38.0
- Close #1010
=> chore: bump trivy 0.38.0

pkg/kube/secrets.go, pkg/kube/secrets_test.go, pkg/plugins/trivy/flags.go, pkg/vulnerabilityreport/controller/workload.go
trivy scan with multi secret support
- Close #790
- Depend #1011
=> feat: multi secret support

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/specs/pss-baseline.yaml, deploy/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.12.0-rc

docs/getting-started/installation/helm.md, docs/tutorials/private-registries.md
Update managed private registries links and helm uninstall crds
=> docs: private managed registries & helm uninstall

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/specs/pss-baseline.yaml, deploy/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.12.0

deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
=> chore: bump trivy-0.38.1

.github/workflows/release-snapshot.yaml, .github/workflows/release.yaml
chore: revert cosign version to 2.8.1
=> chore: revert cosign version to 2.8.1

deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
=> bump-trivy-0.38.2

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/specs/pss-baseline.yaml, deploy/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> feat: release prepare-v0.12.1-rc

deploy/helm/Chart.yaml, deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml, deploy/specs/pss-baseline.yaml, deploy/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.12.1

tests/config/client-server.yaml, tests/config/fs-mode.yaml, tests/config/image-private-registries-config.yaml, tests/config/image-private-registries-sa.yaml, tests/config/image-private-registries.yaml, tests/config/node-collector.yaml, tests/e2e/image-private-registries-sa/data/workload/00-assert.yaml, tests/e2e/image-private-registries-sa/data/workload/00-pod.yaml, tests/e2e/image-private-registries-sa/data/workload/01-assert.yaml
=> test: e2e private registries

.github/workflows/private-registries.yaml
private registries e2e naming change
=> chore: private registries e2e

pkg/webhook/webhookreporter.go
Operator send duplicate report to webhook
- Close #1041 
- Close #1009
=> fix: report send duplicate report to webhook

docs/tutorials/grafana-dashboard.md
prometheus port-forward issue
- Close #1098
=> docs: prometheus port-forward issue

docs/tutorials/grafana-dashboard.md
based on this discussion https://github.com/aquasecurity/trivy-operator/issues/1098#issuecomment-1485080425
=> docs: updating prometheus values in tutorial

CONTRIBUTING.md, docs/tutorials/microk8s.md
docs update - remove starboard entries
=> docs: remove starboards entries

build/trivy-operator/Dockerfile
fix security CVE-2023-0464
- Close #1124
=> fix: CVE-2023-0464

deploy/helm/Chart.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.13.0-rc

deploy/helm/Chart.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.13.0-rc2

deploy/helm/Chart.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.13.0-rc3

deploy/helm/Chart.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.13.0

deploy/helm/templates/trivy-server.yaml
=> feat: propagate proxy settings to trivy server

deploy/helm/templates/config.yaml
Move end blocks where they belong
- Close #1149
=> fix(helm): move end blocks in config.yaml

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.13.1-rc

pkg/operator/operator.go
ttl config when VulnerabilityScanner is not enabled
- Close #1165
=> fix: ttl config when VulnerabilityScanner is not enabled

deploy/helm/templates/trivy-server.yaml
imagePullSecret client/server mode
- Close #1173
=> chore: imagePullSecret for trivy-server image

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.13.1-rc2

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.13.1

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.13.2-rc

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.13.2

deploy/helm/crds/aquasecurity.github.io_clustercompliancereports.yaml, deploy/static/trivy-operator.yaml, pkg/apis/aquasecurity/v1alpha1/compliance_types.go
compliance crd output wide support
- Close #829
=> chore: compliance crd output wide support

go.mod, go.sum, pkg/policy/policy.go
fix kubelet config check 
- Close #1181
=> fix: check kubelet config

pkg/operator/envtest/testdata/fixture/cronjob-expected-scan.yaml, pkg/operator/envtest/testdata/fixture/daemonset-expected-scan.yaml, pkg/operator/envtest/testdata/fixture/job-expected-scan.yaml, pkg/operator/envtest/testdata/fixture/pod-expected-scan.yaml, pkg/operator/envtest/testdata/fixture/replicaset-expected-scan.yaml, pkg/operator/envtest/testdata/fixture/replicationcontroller-expected-scan.yaml, pkg/operator/envtest/testdata/fixture/statefulset-expected-scan.yaml, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
image config secret scanner support
- Close #1198
=> feat: image config secret scanner support

deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml
compliance cron expression with quotes
- Close #1190
=> chore: compliance cron quotes

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.14.0-rc

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.14.0 official

go.mod, go.sum, pkg/configauditreport/controller/node.go
node collector custom annotation support 
- Close #1257
=> feat: node collector annotation support

deploy/helm/README.md, docs/getting-started/installation/helm.md
I have added an additional section to the Helm installation docs to point out to people how they can customise the Helm Chart.
- Close #1266
=> docs: pointing out Helm Chart customisation

deploy/helm/templates/config.yaml, deploy/helm/templates/rbac.yaml, deploy/helm/values.yaml, pkg/trivyoperator/config.go, pkg/trivyoperator/config_test.go
azure workload identity support
- Close #1057
=> feat: azure workload identity support

deploy/helm/templates/trivy-server.yaml, deploy/helm/values.yaml
=> chore: configure server security context

build/trivy-operator/Dockerfile
fix CVE-2023-2650
- Close #1274
=> chore: fix CVE-2023-2650

docs/docs/vulnerability-scanning/managed-registries.md
azure workload identity tutorial
- Related #1057
=> docs: azure workload identity

deploy/helm/README.md, deploy/helm/templates/config.yaml, deploy/helm/templates/rbac.yaml, deploy/helm/values.yaml
remove workload identity helm settings
- Close #1057
=> chore: remove workload identity helm settings

.github/workflows/build.yaml, Makefile
verify helm docs
- Related #1240
=> chore: verify helm docs

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.14.1-rc

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.14.1

README.md
=> docs: update artifacthub badge url

pkg/plugins/trivy/plugin.go
config secret scan fs mode
- Close #1297
=> fix: config secret scan fs mode

deploy/helm/values.yaml
Fixes a link in the helm chart values.yaml comments, it pointed to nowhere.
=> fix: link to documentation

pkg/compliance/io.go
Enrich compliance report role checks data
- Close #1308
=> feat: enrich compliance report with rbac assessment checks data

pkg/plugins/trivy/model.go
pkgPath name update
- Close #1334
=> fix: pkgPath name name update

pkg/plugins/trivy/plugin.go
Fixes an issue where client server setups create multiple volume mounts for ignore files, failing with a "Duplicate value" error
=> Fix ClientServer scan

docs/docs/crds/sbom-report.md, pkg/sbomreport/builder.go, pkg/vulnerabilityreport/controller/scanjob.go
Remove sbom report ttl
- Related #143
=> fix: remove sbom report  ttl

README.md
docs: add outdated api to readme
=> docs: add outdated api to readme

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.15.0

pkg/operator/envtest/controller_test.go, pkg/operator/envtest/suite_test.go, pkg/vulnerabilityreport/controller/helper.go, pkg/vulnerabilityreport/controller/scanjob.go, pkg/vulnerabilityreport/controller/workload.go
Respect disabled exposed secrets
- Close #1369
=> fix: respect disabled exposed secrets

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.15.1

deploy/helm/README.md, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/sbom-report.md, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
=> chore: bump trivy 0.43.1

.github/workflows/private-registries.yaml
=> test: disable global secret

docs/getting-started/installation/helm.md
Minor syntax fix to the custom values.yaml details in the helm docs
- Close #XXX
=> Minor syntax fix to the custom values.yaml details in the helm docs

.github/workflows/validate-chart-appVersion.yaml
Add chart appVersion validation action
- Close #701
=> chore: add chart appVersion validation action

.github/workflows/validate-chart-appVersion.yaml
Add chart appVersion validation action
- Related #701
=> chore: refactor workflow naming

.github/workflows/private-registries.yaml, .github/workflows/validate-chart-appVersion.yaml, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.16.0-rc

magefile.go
mage namespaces support
- Related #1241
=> chore: mage namespaces support

.github/workflows/publish-docs.yaml, .github/workflows/publish-helm-chart.yaml, .github/workflows/release.yaml, .github/workflows/validate-chart-appVersion.yaml
=> chore: trigger chart publish

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, mkdocs.yml
=> release: prepare v0.16.0

.github/workflows/publish-docs.yaml, .github/workflows/publish-helm-chart.yaml
=> chore: action latest tag

.github/workflows/build.yaml, .github/workflows/chart-testing.yaml, .github/workflows/private-registries.yaml, .github/workflows/publish-docs.yaml, .github/workflows/publish-helm-chart.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/release.yaml, .github/workflows/validate-chart-appVersion.yaml
chore: bump chore/checkout-action v4
=> chore: bump chore/checkout-action v4

.github/workflows/release-snapshot.yaml
=> chore: clean cache tools

.github/workflows/release-snapshot.yaml
=> chore: clean cache tools-revert

.github/workflows/release-snapshot.yaml
=> chore: clean cache

.github/workflows/release.yaml
=> chore: clean release cache

build/trivy-operator/Dockerfile
chore: alpine vulnerabilities
- Close #1501
=> chore: alpine vulnerabilities

deploy/helm/README.md, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml
=> chore: bump node collector 0.8.0

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.16.1

.github/workflows/release.yaml
=> chore: remove cache release

pkg/metrics/collector.go
create every vulnerability metric occurrence
- Close #1409
=> fix: create-every vulnerability metric occurence

deploy/helm/templates/trivy-server/statefulset.yaml
trivy-server no-proxy setting
- Close #1503
=> fix: trivy-server no-proxy setting

.github/pr-title-checker-config.json, .github/workflows/title_checker.yaml
=> add-title-checker

.github/pr-title-checker-config.json
=> chore: title-checker-update

.github/workflows/build.yaml, .github/workflows/title_checker-labeler.yaml
=> chore: add workflow deps

.github/pr-prefix-labeler.yml, .github/workflows/title_checker-labeler.yaml
=> chore: merge label tasks

.github/release.yml
=> chore: add automatic release

.github/release.yml
=> chore: add automatic release-lint

docs/getting-started/installation/kubectl.md
Doc fix, very small #hacktoberfest and thank you for this good product! 
- Close #XXX
=> docs: update link to the configuration page in kubectl page

magefile.go
=> chore: helm docs verify

.github/workflows/build.yaml, .github/workflows/private-registries.yaml, .golangci.yml, deploy/helm/README.md, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, go.mod, go.sum, pkg/configauditreport/controller/node.go, pkg/kube/object_test.go, pkg/metrics/collector.go, pkg/vulnerabilityreport/controller/trivyserver_test.go
node-collector resources config
- Close #1541
=> feat: node-collector resources config

.github/workflows/title_checker-labeler.yaml
=> ci: pr title validate

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.16.2

.github/workflows/chart-testing.yaml
=> chore: remove workflow cache

RELEASING.md
=> docs: update release process

pkg/metrics/collector.go
vuln-id metric broken
- Close #1578
=> fix: vuln-id metric broken

.goreleaser.yaml
=> chore: release changlog

deploy/helm/README.md, deploy/helm/templates/configmaps/policies.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml
=> fix(helm): add custom policies config

pkg/plugins/doc.go, pkg/plugins/trivy/config.go, pkg/plugins/trivy/config_test.go, pkg/plugins/trivy/filesystem.go, pkg/plugins/trivy/image.go, pkg/plugins/trivy/image_test.go, pkg/plugins/trivy/jobspec.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
refactor: break plugin pod spec builder
- Related #1307
=> refactor: break plugin pod spec builder

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/grafana-dashboard.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.16.4

deploy/helm/README.md, deploy/helm/templates/configmaps/trivy.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, pkg/plugins/trivy/config.go, pkg/plugins/trivy/filesystem.go, pkg/plugins/trivy/image.go, pkg/plugins/trivy/plugin_test.go
=> feat: Flag for changing default cache-dir parameter

docs/tutorials/grafana-dashboard.md
Get the chart version from environment variables directly
=> fix:  chart version

docs/tutorials/private-registries.md
Get the chart version from environment variables directly
=> docs: fix chart version

pkg/plugins/trivy/image.go, pkg/plugins/trivy/image_test.go
refactor: refactor scan-job command and args
=> refactor: refactor scan-job command and args

pkg/exposedsecretreport/io.go, pkg/plugins/trivy/config.go, pkg/plugins/trivy/config_test.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/sbomreport/io.go, pkg/sbomreport/util.go, pkg/vulnerabilityreport/io.go
refactor: refactor scan-job reports
=> refactor: scan-job reports

docs/getting-started/installation/olm.md
=> docs: Typo fix

go.mod, go.sum
fix: remove node selector
- Close #1635 
- Close #1610 1610
=> fix: remove node selector

pkg/operator/operator.go
fix: ensure trivy cm default
- Close #1584
=> fix: ensure trivy cm default

.github/workflows/publish-helm-chart.yaml
chore: add condition for docs publish
=> chore: add condition for docs publish

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml, pkg/metrics/collector.go, pkg/plugins/trivy/plugin.go
=> release: prepare v0.17.0-rc

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.17.0

pkg/plugins/trivy/plugin.go, pkg/vulnerabilityreport/controller/scanjob.go
Protect nil pointer and error handling
- Close #1663
=> fix: scan job fail nil pointer

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.17.1

deploy/helm/README.md, deploy/helm/templates/configmaps/trivy.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, pkg/plugins/trivy/config.go, pkg/plugins/trivy/config_test.go, pkg/plugins/trivy/filesystem.go, pkg/plugins/trivy/filesystem_test.go
feat: trivy fs -include-dev-deps support
- Close #1620
=> feat: trivy fs -include-dev-deps support

docs/getting-started/installation/helm.md
Removed duplicate CRD entry in the list
=> docs: remove duplicate entry in the CRDs list

mkdocs.yml
While I got a chuckle out of "Complain-ce", I figured I'd just send a PR to fix.
- [n/a] I've added tests that prove my fix is effective or that my feature works.
- [n/a] I've added usage information (if the PR introduces new options)
- [n/a] I've included a "before" and "after" example to the description (if the PR is a user interface change).
=> fix: typo in nav

pkg/vulnerabilityreport/controller/helper.go, pkg/vulnerabilityreport/controller/helper_test.go, pkg/vulnerabilityreport/controller/testdata/sbom.json
Sbom secret size limit support
- Close #1680
=> fix: sbom secret size limit

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.18.0-rc

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.18.0-rc2

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
release: prepare v0.18.0 official
=> release: prepare v0.18.0 official

.github/workflows/private-registries.yaml, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/docs/vulnerability-scanning/managed-registries.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.18.1

tests/e2e/image-private-registries-config/workload/00-assert.yaml, tests/e2e/image-private-registries-config/workload/00-pod.yaml, tests/e2e/image-private-registries-config/workload/01-assert.yaml, tests/e2e/image-private-registries-sa/data/workload/00-assert.yaml, tests/e2e/image-private-registries-sa/data/workload/00-pod.yaml, tests/e2e/image-private-registries-sa/data/workload/01-assert.yaml, tests/e2e/image-private-registries-sa/manifests/sa.yaml, tests/e2e/image-private-registries/workload/00-assert.yaml, tests/e2e/image-private-registries/workload/00-pod.yaml, tests/e2e/image-private-registries/workload/01-assert.yaml
=> test: private registries

pkg/operator/operator.go
improve cluster version handling
- Close #1767
=> fix: cluster version support

tests/config/client-server-sbom.yaml, tests/config/fs-sbom.yaml, tests/config/sbom-standalone.yaml, tests/resources-cleanup.sh
test: e2e with sbom - fluky tests
=> test: e2e with sbom - fluky tests

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.18.2

docs/tutorials/private-registries.md
=> fix: update private-registries.md

README.md
=> docs: helm version

CONTRIBUTING.md, README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.18.3

deploy/helm/README.md, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml
=> chore: disable cluster cache

docs/tutorials/integrations/metrics.md
Fixes markdown issue in metrics.md file.
=> docs: Fix formatting in docs/tutorials/integrations/metrics.md

README.md
=> fix:  markdown url mistakes

deploy/helm/README.md, deploy/helm/templates/configmaps/trivy.yaml, deploy/helm/values.yaml
=> feat: config for insecure server registry connection

CONTRIBUTING.md, README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.18.4

CONTRIBUTING.md, README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.18.5

pkg/configauditreport/controller/helper.go
feat: opa exception support
- Close #1742
=> feat: opa exception support

deploy/helm/README.md, deploy/helm/values.yaml, pkg/apis/aquasecurity/v1alpha1/common_types.go, pkg/operator/etc/config.go, pkg/operator/operator.go, pkg/operator/ttl_report.go, pkg/vulnerabilityreport/builder.go, pkg/vulnerabilityreport/controller/workload.go, tests/config/image-private-registries.yaml, tests/e2e/image-private-registries/workload/02-assert.yaml
feat: scan job secret ttl support
- Close #1855
-
=> feat: scan job secret ttl support

tests/e2e/image-private-registries/workload/02-assert.yaml
=> test: scan-job secret ttl

CONTRIBUTING.md, README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/index.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.19.0

deploy/helm/values.yaml
update ignore file values example
=> chore: update ignore file values example

CONTRIBUTING.md, README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/index.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.19.2

overrides/main.html
Clean-up un-used folders and files
=> chore: clean-up un-used folders and files

CONTRIBUTING.md, README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_trivy_file_system_scanner.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/index.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.19.4

deploy/helm/values.yaml
=> fix: Updates ignorePolicy comments in values.yaml

pkg/policy/loader.go, pkg/policy/policy.go
Add policies download err msg and fallback to embeded
- Close #1999
=> fix: add policies download err msg and fallback to embeded

pkg/policy/loader.go
fix: log entry name on policy loader
=> fix: log entry name on policy loader

deploy/helm/README.md, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml
Better handling for kubelet config
- Close #1970
=> fix: better handling for kubelet config

RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_trivy_file_system_scanner.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.20.0

CONTRIBUTING.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_trivy_file_system_scanner.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/getting-started/installation/olm.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.20.1

.github/workflows/build.yaml, .github/workflows/chart-testing.yaml, .github/workflows/private-registries.yaml, .github/workflows/release.yaml, go.mod
fix:  cves high and critical
- Close #2076
=> fix:  cves high and critical

deploy/helm/README.md, deploy/helm/templates/configmaps/operator.yaml, deploy/helm/values.yaml, pkg/plugins/trivy/filesystem.go, pkg/plugins/trivy/image.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/trivyoperator/config.go, pkg/trivyoperator/config_test.go, pkg/vulnerabilityreport/controller/workload.go
Filter container by regex
- Close #2002
=> feat: filter container by regex

CONTRIBUTING.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_trivy_file_system_scanner.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/getting-started/installation/olm.md, docs/tutorials/private-registries.md, tests/itest/helper/helper.go
=> release: prepare v0.21.0

deploy/helm/Chart.yaml, deploy/helm/README.md, mkdocs.yml
=> release: helm v0.23.0

build/trivy-operator/Dockerfile
sec: fix cve-2023-42366 and CVE-2024-2511 
- Close #2086
=> sec: CVE-2023-42366 and CVE-2024-2511 

.github/workflows/build.yaml, .github/workflows/chart-testing.yaml, .github/workflows/private-registries.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/release.yaml
chore: auto bump minor golang version
=> chore: auto bump minor golang version

CONTRIBUTING.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_trivy_file_system_scanner.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/getting-started/installation/olm.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.21.1

pkg/vulnerabilityreport/controller/scanjob.go
log failed container error
- Related #2101
=> fix: log failed container error

pkg/plugins/trivy/config.go, pkg/vulnerabilityreport/builder.go, pkg/vulnerabilityreport/builder_test.go, pkg/vulnerabilityreport/controller/scanjob.go
fix: set default value for useBuiltIntPolicies
- Close #2113
=> fix: set default value for useBuiltIntPolicies

CONTRIBUTING.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_trivy_file_system_scanner.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/getting-started/installation/olm.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.21.2

CONTRIBUTING.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_trivy_file_system_scanner.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/getting-started/installation/olm.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.21.3

docs/docs/crds/sbom-report.md
=> docs: fix typos in SbomReport docs

CONTRIBUTING.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/eks-cis-1.4.yaml, deploy/helm/templates/specs/k8s-cis-1.23.yaml, deploy/helm/templates/specs/k8s-nsa-1.0.yaml, deploy/helm/templates/specs/k8s-pss-baseline-0.1.yaml, deploy/helm/templates/specs/k8s-pss-restricted-0.1.yaml, deploy/helm/templates/specs/rke2-cis-1.24.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_trivy_file_system_scanner.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/getting-started/installation/olm.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.22.0

deploy/helm/Chart.yaml, deploy/helm/README.md
=> chore: Update chart 0.24.1

docs/tutorials/grafana-dashboard.md
=> docs: fix typo

CONTRIBUTING.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/eks-cis-1.4.yaml, deploy/helm/templates/specs/k8s-cis-1.23.yaml, deploy/helm/templates/specs/k8s-nsa-1.0.yaml, deploy/helm/templates/specs/k8s-pss-baseline-0.1.yaml, deploy/helm/templates/specs/k8s-pss-restricted-0.1.yaml, deploy/helm/templates/specs/rke2-cis-1.24.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/clustervulnerability-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/infraassessment-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/crds/sbom-report.md, docs/docs/crds/vulnerability-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_trivy_file_system_scanner.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/getting-started/installation/olm.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.23.0

README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/eks-cis-1.4.yaml, deploy/helm/templates/specs/k8s-cis-1.23.yaml, deploy/helm/templates/specs/k8s-nsa-1.0.yaml, deploy/helm/templates/specs/k8s-pss-baseline-0.1.yaml, deploy/helm/templates/specs/k8s-pss-restricted-0.1.yaml, deploy/helm/templates/specs/rke2-cis-1.24.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/clustervulnerability-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/infraassessment-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/crds/sbom-report.md, docs/docs/crds/vulnerability-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_trivy_file_system_scanner.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.24.0

.github/workflows/publish-helm-chart.yaml
This PR updates installed python version for Helm Chart forkflow to fix:
https://github.com/aquasecurity/trivy-operator/actions/runs/13191791193/job/36825958183
=> fix(ci): update python action for Helm chart testing

docs/tutorials/writing-custom-configuration-audit-policies.md
This PR fixes the indentation in the data field and makes the rule match the metadata.
=> docs: correct example ConfigMap for custom policy

.github/workflows/build.yaml, README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/eks-cis-1.4.yaml, deploy/helm/templates/specs/k8s-cis-1.23.yaml, deploy/helm/templates/specs/k8s-nsa-1.0.yaml, deploy/helm/templates/specs/k8s-pss-baseline-0.1.yaml, deploy/helm/templates/specs/k8s-pss-restricted-0.1.yaml, deploy/helm/templates/specs/rke2-cis-1.24.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.24.1

.github/dependabot.yml
ci: Add groupings to dependabot.yml
=> ci: Add groupings to dependabot.yml

README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/eks-cis-1.4.yaml, deploy/helm/templates/specs/k8s-cis-1.23.yaml, deploy/helm/templates/specs/k8s-nsa-1.0.yaml, deploy/helm/templates/specs/k8s-pss-baseline-0.1.yaml, deploy/helm/templates/specs/k8s-pss-restricted-0.1.yaml, deploy/helm/templates/specs/rke2-cis-1.24.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.25.0

pkg/policy/policy.go, pkg/policy/policy_test.go
=> fix(misconfig): ordering policies for hash

docs/docs/crds/clustervulnerability-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/infraassessment-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/crds/sbom-report.md, docs/docs/crds/vulnerability-report.md, docs/docs/design/design_trivy_file_system_scanner.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md
This PR updates some samples with the latest Trivy version
=> docs: bump up Trivy version in the samples

.github/workflows/build.yaml, .github/workflows/release.yaml
Frees up additional space during build time.
=> chore(ci): Free up additional space

pkg/plugins/trivy/plugin_test.go
This PR adds a few test cases to clarify `excludeImages` option.
- Close #2532
=> test: add test cases for exclude images

.github/workflows/build.yaml, .golangci.yml, magefile.go, pkg/plugins/trivy/plugin_test.go
chore(deps): bump golangci-lint to v2.1.2
=> chore(deps): bump golangci-lint to v2.1.2

.golangci.yml, pkg/configauditreport/controller/helper_test.go, pkg/docker/config.go, pkg/kube/logs.go, pkg/operator/cluster.go, pkg/plugins/trivy/config.go, pkg/plugins/trivy/plugin_test.go
This enable and fixes most of staticcheck issues
=> fix: enable staticcheck linters

pkg/plugins/trivy/image.go, pkg/plugins/trivy/jobspec.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
Reverts aquasecurity/trivy-operator#2590
=> revert: "fix: login private registry instead of download JavaDB"

README.md, deploy/helm/Chart.yaml, deploy/helm/README.md, mkdocs.yml
chore: bump helm chart version
- Close https://github.com/aquasecurity/trivy-operator/issues/2604
=> chore: bump helm chart version

deploy/helm/templates/pvc.yaml
=> fix(deploy): remove hardcoded namespace from pvc-template

README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/eks-cis-1.4.yaml, deploy/helm/templates/specs/k8s-cis-1.23.yaml, deploy/helm/templates/specs/k8s-nsa-1.0.yaml, deploy/helm/templates/specs/k8s-pss-baseline-0.1.yaml, deploy/helm/templates/specs/k8s-pss-restricted-0.1.yaml, deploy/helm/templates/specs/rke2-cis-1.24.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/index.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.27.3

build/trivy-operator/Dockerfile.ubi9
chore: update for CVE-2025-6965
=> chore: update for CVE-2025-6965

README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/specs/eks-cis-1.4.yaml, deploy/helm/templates/specs/k8s-cis-1.23.yaml, deploy/helm/templates/specs/k8s-nsa-1.0.yaml, deploy/helm/templates/specs/k8s-pss-baseline-0.1.yaml, deploy/helm/templates/specs/k8s-pss-restricted-0.1.yaml, deploy/helm/templates/specs/rke2-cis-1.24.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/index.md, docs/tutorials/private-registries.md, mkdocs.yml, tests/itest/helper/helper.go
=> release: prepare v0.28.0
