aquasecurity/trivy-operator

pkg/plugin/conftest/plugin.go, pkg/plugin/conftest/plugin_test.go, pkg/plugin/polaris/plugin_test.go, pkg/plugin/trivy/plugin_test.go, pkg/trivyoperator/config_test.go, pkg/trivyoperator/plugin.go, pkg/trivyoperator/plugin_test.go
- Close https://github.com/aquasecurity/trivy-operator/issues/41
=> fix: fix plugin configmap name

deploy/crd/ciskubebenchreports.crd.yaml, deploy/crd/clustercompliancedetailreports.crd.yaml, deploy/crd/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/clustervulnerabilityreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/kubehunterreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml
Signed-off-by: David <davidcalvertfr@gmail.com>
- This is a fix proposal for https://github.com/aquasecurity/trivy-operator/issues/58
- Bumped helm chart version to 0.0.4
Another solution would be to add a category, but this fix seemed more appropriate to me.
Let me know if any change is needed for this PR.
David
Screenshots (theses were made with starboard but it's the same code):
- Broken: https://raw.githubusercontent.com/dotdc/media/main/github-issues/2022-05-30-starboard-crds-broken.png
- Diff Detail : https://raw.githubusercontent.com/dotdc/media/main/github-issues/2022-05-30-starboard-crds-detail.png
- Fixed: https://raw.githubusercontent.com/dotdc/media/main/github-issues/2022-05-30-starboard-crds-fixed.png
- Close #58 
=> fix: issue #58 trivy-operator CRDs out-of-sync on ArgoCD

README.md
add ref to trivy-operator mkdocs
- Close #46 
=> docs: add ref to trivy-operator mkdocs

deploy/crd/configauditreports.crd.yaml, deploy/static/trivy-operator.yaml
Add plural to configauditreport crd.
Before:
```
configauditreports                configaudit                    aquasecurity.github.io/v1alpha1        true         ConfigAuditReport
```
After:
```
configauditreports                configaudit,configaudits   aquasecurity.github.io/v1alpha1        true         ConfigAuditReport
```
- Close #112 
- [x ] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ x] I've included a "before" and "after" example to the description (if the PR is a user interface change).
=> add plural to configauditreport crd

docs/operator/getting-started.md, itest/helper/helper.go, itest/matcher/matcher.go, itest/matcher/matcher_test.go, pkg/apis/aquasecurity/v1alpha1/common_types.go, pkg/compliance/testdata/fixture/configAuditReportList.json, pkg/configauditreport/controller.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go, pkg/trivyoperator/config_test.go
Change the scanner property on configaudit resources from `Trivy-Operator` to `Trivy`.
- Close #107
=> fix: ConfigAudit scanner should be Trivy

deploy/static/05-trivy-operator.deployment.yaml, deploy/static/trivy-operator.yaml, go.mod, pkg/metrics/collector.go, pkg/metrics/collector_test.go, pkg/metrics/metrics_suite_test.go, pkg/operator/etc/config.go, pkg/operator/operator.go
This adds a leader-election aware custom Prometheus collector. This collector produces metrics from `VulnerabilityReport` summary, but can easily be extended to produce other metrics from trivy-operator custom resources.
- related to (but doesn't close) #78 
=> feat: add VulnerabilityReport summary metrics

deploy/crd/vulnerabilityreports.crd.yaml, deploy/static/trivy-operator.yaml, pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go, pkg/plugin/trivy/model.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go
This PR aims to add the target scan field from trivy to the vulnerabilities in the `vulnerabilityreport`
If I've forgotten anything, I'd love to hear about it
Example
- Close #106
=> feat: add scan target to vulnerabilities

pkg/apis/aquasecurity/v1alpha1/config_audit_types.go, pkg/apis/aquasecurity/v1alpha1/zz_generated.deepcopy.go, pkg/configauditreport/controller.go
before:
```
kubectl describe configaudit replicaset-app-574ddcb559 | grep "Check ID" | sort
Check ID:     KSV001
Check ID:     KSV001
Check ID:     KSV002
Check ID:     KSV002
Check ID:     KSV003
Check ID:     KSV003
Check ID:     KSV004
Check ID:     KSV004
Check ID:     KSV005
Check ID:     KSV005
Check ID:     KSV006
Check ID:     KSV006
Check ID:     KSV007
Check ID:     KSV007
Check ID:     KSV008
Check ID:     KSV008
Check ID:     KSV009
Check ID:     KSV009
Check ID:     KSV010
Check ID:     KSV010
Check ID:     KSV011
Check ID:     KSV011
Check ID:     KSV012
Check ID:     KSV012
Check ID:     KSV013
Check ID:     KSV013
Check ID:     KSV014
Check ID:     KSV014
Check ID:     KSV015
Check ID:     KSV015
Check ID:     KSV016
Check ID:     KSV016
Check ID:     KSV017
Check ID: …
```
=> fix: remove dups on configaudit report

deploy/helm/templates/config.yaml, deploy/helm/values.yaml, docs/vulnerability-scanning/trivy.md, pkg/plugin/trivy/plugin.go
support insecure flag for download trivy-db
- Close #127
=> fix: support insecure flag for download trivy-db

hack/update-static.yaml.sh
Sadly there was a bug in the script add in https://github.com/aquasecurity/trivy-operator/pull/176. Sorry for that! This fixes the script to use the correct environment variable name.
=> fix: use correct env name in update-static.yaml.sh

deploy/helm/templates/rbac.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml
Adds new aggregated view clusterroles for default user-facing roles. I have tested this on a multi-tenant Openshift cluster, and while I earlier was not allowed to see any trivy custom resources as a regular user, I can not view all resources:
- Close #173 
=> feat: add aggregated view clusterroles for default user-facing roles

deploy/helm/templates/rbac.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml
exposedsecretreports are missing from trivy-operator clusterrole
- Close #197
=> fix: exposedsecretreports are missing from trivy-operator clusterrole

docs/vulnerability-scanning/trivy.md
trivy client/serverurl and standalon urls are broken
- Close #189 
-
=> docs: trivy client/serverurl and standalon urls are broken

deploy/helm/templates/leader_election.yaml, deploy/helm/templates/rbac.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml, hack/update-static.yaml.sh
This change withdraws some unneeded cluster-wide RBAC permissions and replaces them with equivalent operator namespace permissions - that are required to perform operator leader-election. To make it more obvious **why** permissions are needed, I put the new Role/RoleBinding in a dedicated file. This is also how kubebuilder scaffolds new projects. I can merge the new resources into the rbac.yaml file if you don't like it, but I prefer what I have suggested.
Technically the operator currently needs permission to create configmaps in the operator namespace, even with no leader election. Ref. https://github.com/aquasecurity/trivy-operator/blob/59452b4b465c1292aa9a763e459cf7f83553fb48/pkg/trivyoperator/plugin.go#L70-L85
But I decided to leave this out for now, since this permission is already …
=> fix: tighten RBAC; remove some unneeded cluster-wide permissions

RELEASING.md
rename crd to kube builder convension
- Close #233
=> docs/rename crd to kube_builder convension

pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go
dbRepositoryInsecure param always return true
- Close #245
=> fix: dbRepositoryInsecure param always return true

deploy/helm/templates/rbac.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml
While analyzing trivy-operator RBAC, I noticed that the user-facing roles introduced in https://github.com/aquasecurity/trivy-operator/pull/175 are missing the labels applied to all trivy-operator resources. This PR fixes that.
- Close #173
=> fix: add missing trivy-operator labels to user-facing roles

deploy/helm/templates/leader_election.yaml, deploy/helm/templates/rbac.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml
Since version 0.12.0 (https://github.com/kubernetes-sigs/controller-runtime/commit/6c4d94736d88495da30a4241dec034b0fa177d94), controller-runtime uses `leases` as default resource lock object (was `configmapsleases`), which means that trivy-operator no longer needs update permission on operator-namespace configmaps.
Just a tiny RBAC improvement, but also on the path to eventually generate clusterroles/roles using controller-gen from code markers.
- Relates to #187, but doesn't fix it. 
- Relates to #204
=> chore: tighten RBAC; default leader election lock is now leases

deploy/compliance/aquasecurity.github.io_clustercompliancedetailreports.yaml, deploy/compliance/aquasecurity.github.io_clustercompliancereports.yaml, deploy/crd/aquasecurity.github.io_clusterconfigauditreports.yaml, deploy/crd/aquasecurity.github.io_clusterrbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_configauditreports.yaml, deploy/crd/aquasecurity.github.io_exposedsecretreports.yaml, deploy/crd/aquasecurity.github.io_rbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_vulnerabilityreports.yaml
diff in 232 is a bit hard to read as the yaml files generated by
controller-gen are sorted alphabetically. This PR makes it a lot easier
to follow the changes introduced by controller-gen in 232.
I used VS Code extension (YAML sort) tool to sort the CRD files.
related to #204
=> sort the yaml files alphabetically

deploy/static/trivy-operator.yaml
It seems like @padlar forgot to regenerate the static resources after the last modifications in #247. This fixes this, as I ran `./hack/update-static.yaml.sh` from HEAD of main branch.
- Blocks #267
=> fix: regenerate static resources (outdated)

deploy/compliance/aquasecurity.github.io_clustercompliancedetailreports.yaml, deploy/compliance/aquasecurity.github.io_clustercompliancereports.yaml, deploy/crd/aquasecurity.github.io_clusterconfigauditreports.yaml, deploy/crd/aquasecurity.github.io_clusterrbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_configauditreports.yaml, deploy/crd/aquasecurity.github.io_exposedsecretreports.yaml, deploy/crd/aquasecurity.github.io_rbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_vulnerabilityreports.yaml, deploy/static/trivy-operator.yaml
Formatting the CRDs with controller-gen Yaml list style (same level as the map key). This will make it easier to review https://github.com/aquasecurity/trivy-operator/pull/232 (less changes). It seems to be impossible to control list indentation in controller-gen.
- Related #204
=> refactor: format CRDs with controller-gen list style

deploy/helm/values.yaml
This removes some values from the Helm chart that seems not in use, and might be confusing to users. In particular the image reference referring to an image that haven't been updated for a year or so: https://hub.docker.com/r/aquasec/scanner
=> chore: remove unused Helm chart values

deploy/helm/values.yaml, deploy/static/03-trivy-operator.config.yaml, deploy/static/trivy-operator.yaml, docs/vulnerability-scanning/trivy.md, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go
This changes the scan job image to be pulled from ghcr.io by default (was docker.io)
- Close #263 
- Close #251
=> feat: pull scan job image from ghcr by default

.github/workflows/build.yaml, CONTRIBUTING.md, Makefile, RELEASING.md
This adds new Makefile targets to generate manifests (currently just a wrapper around the `./hack/update-static.yaml.sh`) and to regenerate all checked in generated resources. I've tested that CI picks up outdated static resources now. I was a bit surprised to see that Helm already was installed in the CI image. 😉 
Also updating the contributor and releasing docs.
- Close #207
=> chore: make CI verify all generated is up-to-date

pkg/kube/secrets.go, pkg/kube/secrets_test.go, pkg/kube/testdata/fixture/sa_secret.json, pkg/kube/testdata/fixture/sa_with_image_pull_secret.json, pkg/kube/testdata/fixture/sa_without_image_pull_secret.json, pkg/kube/testdata/fixture/secret.json
Getting imagePullSecrets should fail only if not exist in pod spec and service account
- Close #266
=> fix: getting imagePullSecrets should fail only if not exist in pod spec and service account

.github/workflows/release-snapshot.yaml, .github/workflows/release.yaml, .goreleaser.yaml
This uses cosign to generate artifact signatures.
The proposed configuration will use the GitHub Actions token to sign the
generated artifacts (from goreleaser's artifacts pipeline), as well as
any generated containers.
Once a container is published, verification can be done with the
following command:
```bash
$ COSIGN_EXPERIMENTAL=1 cosign verify <container name>
```
Note that the current setup limits running goreleaser in GitHub Actions (or at
least with a GitHub token available)
- Close #XXX
=> Add signature generation to goreleaser configuration

.github/workflows/release.yaml
This trims down the permissions for the release GitHub workflow. Thus,
now only adding to the OIDC token the needed permissions.
- Close #XXX
=> Use explicit permissions for release workflow

Makefile, RELEASING.md, deploy/compliance/aquasecurity.github.io_clustercompliancedetailreports.yaml, deploy/compliance/aquasecurity.github.io_clustercompliancereports.yaml, deploy/crd/aquasecurity.github.io_clusterconfigauditreports.yaml, deploy/crd/aquasecurity.github.io_clusterrbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_configauditreports.yaml, deploy/crd/aquasecurity.github.io_exposedsecretreports.yaml, deploy/crd/aquasecurity.github.io_rbacassessmentreports.yaml, deploy/crd/aquasecurity.github.io_vulnerabilityreports.yaml, deploy/static/trivy-operator.yaml, pkg/apis/aquasecurity/v1alpha1/compliance_types.go, pkg/apis/aquasecurity/v1alpha1/compliancedetail_types.go, pkg/apis/aquasecurity/v1alpha1/config_audit_types.go, pkg/apis/aquasecurity/v1alpha1/exposed_secrets_types.go, pkg/apis/aquasecurity/v1alpha1/rbac_assessment_types.go, pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go
Picking up https://github.com/aquasecurity/trivy-operator/pull/232, as @padlar (we are working on the same team) is not available this week, and I want to get this in as soon as possible - as it will allow me/us to suggest improvements to trivy-operator more easily. I have talked to @padlar, and got a confirmation that it's ok to finalize the changes suggested in https://github.com/aquasecurity/trivy-operator/pull/232.
This PR suggests using controller-gen to generate all CRDs from now on. After a couple of pre-PRs, I think this now looks close enough to the currently hand-coded CRDs, and possible to review.
Sadly, the labels currently added to the CRDs (version and managed-by) cannot be sustained with this change, as this is an eschewed feature in controller-gen: …
=> chore: use controller-gen to generate CRDs from Go markers

.github/workflows/release-snapshot.yaml
The token is required for cosign to retrieve a certificate for the
signature. Even if this job won't actually publish anything, it still
does the signing part (which is good to test).
This is fixed by passing the GitHub token to the goreleaser action as an
environment variable.
This also explicitly adds permissions for the job to use OIDC tokens.
- Close #291
=> Pass GitHub token to snapshot workflow's goreleaser action

.github/workflows/release.yaml, .goreleaser.yaml, RELEASING.md
This uses the existing workflow token to publish container images to
GHCR. The advante of using this is that it's already hosted in the same
infrastructure as the jobs that are building the containers, and it uses
existing tokens for authentication; so there's no need to store or
manage secrets for this registry.
- Close #261
=> Also publish container images to GHCR

pkg/operator/jobs/jobs_suite_test.go, pkg/operator/jobs/limit_checker.go, pkg/operator/jobs/limit_checker_test.go, pkg/operator/operator.go, pkg/vulnerabilityreport/controller.go, pkg/vulnerabilityreport/ttl_report.go
This is a small refactoring, mainly to move the `VulnerabilityScannerReport` TTL controller to where it is actually used. Also renamed the `controller` package to `jobs`, since it now only contains the code to check job count limits. Keeping it separate from `VulnerabilityScannerReport`, since it eventually can be reused later.
=> refactor: move TTL controller to where it is used

.goreleaser.yaml
the `-ubi8-amd64` template was missing from the original inclusion of
GHCR to the list of registries we push to. This is now fixed.
=> Add missing GHCR template in goreleaser configuration

.golangci.yml, pkg/configauditreport/controller/controller.go, pkg/plugin/trivy/plugin.go
gosec does static analysis on the go code-base. it's already a linter in
golangci-lint, so enabling it is quite simple.
=> Enable gosec for security linting

deploy/helm/templates/rbac.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml
While working on https://github.com/aquasecurity/trivy-operator/pull/276, I noticed that trivy-operator is granted permissions to read nodes, which it does not need - at least not atm. It might be required when reintroducing CIS Benchmarks ( https://github.com/aquasecurity/trivy-operator/issues/141), but I suggest to remove it for now.
- Relates to #187 
=> chore: remove nodes RBAC permissions from clusterrole

deploy/helm/generated/role.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml
This is a refactoring that organizes the operator clusterrole rules by resource, i.e. one resource per rule. This is how controller-gen generates RBAC from code markers, which makes this PR next in line towards a reviewable PR resolving https://github.com/aquasecurity/trivy-operator/issues/204.
I have a draft PR for the final changes, which shows how this could end up: https://github.com/aquasecurity/trivy-operator/pull/215/files
- Relates to https://github.com/aquasecurity/trivy-operator/issues/204
=> refactor: organize ClusterRole rules by resource

deploy/helm/generated/role.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml
This is the next in line towards resolving https://github.com/aquasecurity/trivy-operator/issues/204. Since controller-gen is sorting the RBAC rules by `apiGroups`, then `resources`, I think it is safest if we do the sorting as a pre-PR before migrating to generating the clusterrole. Please let me know if you can think of a more review-friendly approach...
Next PR before migrating to generating will be yaml lists formatting.
- Relates to #204 
=> refactor: sort ClusterRole rules by apiGroups, resources

deploy/helm/generated/role.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml
This is the next in line towards resolving https://github.com/aquasecurity/trivy-operator/issues/204. Since controller-gen is sorting the RBAC rules verbs, I think it is safest if we do the sorting as a pre-PR before migrating to generating the clusterrole.
Command used to do this: `yq -i '.rules[].verbs |= sort()' deploy/helm/generated/role.yaml`
- Relates to https://github.com/aquasecurity/trivy-operator/issues/204
=> refactor: sort ClusterRole rules[].verbs

deploy/helm/generated/role.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml, pkg/operator/operator.go
This reverts commit 519d9fe3
When investigating https://github.com/aquasecurity/trivy-operator/issues/327, I notice that the operator complains about missing RBAC permissions to list/watch secrets. So I am pretty convinced that the fix proposed and merged in https://github.com/aquasecurity/trivy-operator/pull/276 does not work. This PR reverts it, and https://github.com/aquasecurity/trivy-operator/issues/230 should be reopened.
````
W0715 08:11:25.882410       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:trivy-system:trivy-operator" cannot list resource "secrets" in API group "" at the cluster scope
E0715 08:11:25.882442       1 reflector.go:138] …
```
=> Revert "chore: disable caching of secrets and serviceaccounts (#276)"

CONTRIBUTING.md, Makefile, deploy/helm/generated/role.yaml, deploy/static/02-trivy-operator.rbac.yaml, deploy/static/trivy-operator.yaml, pkg/compliance/clustercompliancereport.go, pkg/configauditreport/controller/controller.go, pkg/kube/logs.go, pkg/kube/secrets.go, pkg/vulnerabilityreport/controller.go, pkg/vulnerabilityreport/ttl_report.go
This PR finalizes the migration to generating the trivy-operator clusterrole from code markers using controller-gen, and will allow us to finally close https://github.com/aquasecurity/trivy-operator/issues/204. We should probably add a few lines to the contributor documentation about how this works, with links to the marker documentation (kubebuilder docs), but that could be a follow-up PR.
I have tried to put markers in the code close to the relevant code creating the requirement for permissions. In some cases that leads to the same requirement for a permission being expressed in multiple places. But this is deduplicated by controller-gen, and IMO it makes a lot of sense to do it, since it will allow us to adjust the code and RBAC requirements from the same "page". I.e. when deleting …
=> chore: generate ClusterRole from RBAC markers

pkg/kube/secrets.go, pkg/kube/secrets_test.go
Working with new integration tests, I was bugged by #305, so here is a PR to fix it.
- Close #305
=> fix: should not error when serviceaccount not found

build/trivy-operator/Dockerfile
This upgrades the uptream alpine image to `3.16.1`. ~~I attempted the workaround suggested in https://github.com/alpinelinux/docker-alpine/issues/261#issuecomment-1186281774, but that didn't work (package conflicts).~~ Update: New patched image tag just released.
````
D:~/projects/github/trivy-operator (fix/workaround-image-vuln) $ make docker-build
CGO_ENABLED=0 GOOS=linux go build -o ./bin/trivy-operator ./cmd/trivy-operator/main.go
docker build --no-cache -t aquasec/trivy-operator:dev -f build/trivy-operator/Dockerfile bin
[+] Building 3.1s (8/8) FINISHED
=> [internal] load build definition from Dockerfile                                                               0.1s
=> => transferring dockerfile: 225B …
```
=> fix: use upstream alpine 3.16.1 image (fix CVE-2022-2097)

pkg/configauditreport/controller/controller.go, pkg/policy/policy.go, pkg/policy/policy_test.go
update policies not trigger rescan after operator startup
- Close #351 
- [ x I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
=> fix: update policies not trigger rescan after operator startup

.golangci.yml, pkg/compliance/clustercompliancereport_test.go, pkg/configauditreport/controller/controller.go, pkg/configauditreport/controller_test.go, pkg/kube/object.go, pkg/plugins/trivy/model_test.go, pkg/plugins/trivy/plugin.go, pkg/trivyoperator/constants_test.go, pkg/vulnerabilityreport/controller_test.go, pkg/vulnerabilityreport/plugin_test.go, pkg/vulnerabilityreport/scanner_test.go
This renovates the golangci-lint configuration by:
- Sorting keys/list alphabetically
- Remove enabling [linters that are enabled by default](https://golangci-lint.run/usage/linters/#enabled-by-default)
- Enabling all linters enabled by default in golangci-lint, except the ones that do not yet work on Go 1.18
Fixing some minor issues reported by linters enabled in this PR. Also delete some empty files.
- Relates to https://github.com/aquasecurity/trivy-operator/issues/311
=> refactor: renovate golangci-lint configuration

pkg/vulnerabilityreport/controller.go
That should be only one watcher for cronjob, that will depend on the cluster, and is decided by `r.ObjectResolver.GetSupportedObjectByKind(kube.KindCronJob)}`
- Close https://github.com/aquasecurity/trivy-operator/issues/382
=> fix: remove duplicate cronjob watcher

.github/workflows/release-snapshot.yaml, CONTRIBUTING.md, Makefile, deploy/helm/values.yaml, deploy/static/kustomization.yaml, deploy/static/trivy-operator.yaml
- Close https://github.com/aquasecurity/trivy-operator/issues/262
=> chore: make GHCR the default registry for trivy-operator image

deploy/helm/templates/config.yaml, deploy/helm/values.yaml
Fixes https://github.com/aquasecurity/trivy-operator/issues/372 by adding ''trivy.insecureRegistry" to the helm chart
- Close #372
=> adds 'insecureRegistries' to the helm chart

pkg/configauditreport/controller/controller.go
On k8s 1.19 it is not accepted a zero value metav1.Time, so we need to set it when creating the config audit report like we do for the vulnerability report -> https://github.com/aquasecurity/trivy-operator/blob/main/pkg/plugins/trivy/plugin.go#L1363
- Close https://github.com/aquasecurity/trivy-operator/issues/400
=> fix: set configauditreport updatetimestamp

build/trivy-operator/Dockerfile
fix vulnerability CVE-2022-37434
- Close #424
=> chore: fix CVE-2022-37434

deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, docs/operator/configuration.md, pkg/operator/etc/config.go, pkg/operator/operator.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/trivyoperator/config.go, pkg/trivyoperator/config_test.go, pkg/vulnerabilityreport/controller.go, pkg/vulnerabilityreport/suite_test.go, pkg/vulnerabilityreport/testdata/fixture/cronjob-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/daemonset-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/job-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/pod-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/replicaset-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/replicationcontroller-expected-scan.yaml, pkg/vulnerabilityreport/testdata/fixture/statefulset-expected-scan.yaml
I chose a design for this feature that I would prefer to refactor later, mostly because of https://github.com/aquasecurity/trivy-operator/issues/415. Configurations to enable/disable scanner are considered `operatorConfig`, and are done through env variables, which are not passed in the context of the scanning plugin. Scanning configurations are configured as a ConfigMap, considered `trivyOperatorConfig`, and passed as context to the plugin. Because of this separation I'm setting the options from `operatorConfig` into `trivyOperatorConfig`.  Preferably I think we should only have one source of configuration, ConfigMap for all options related to the operator, which would be passed in the plugin context.
Note, I'm not talking about the …
=> feat: add flag to disable secret scan

deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml
Adds `operator.podLabels` configuration property to allow custom labels for the operator pod.
- Close #464
=> feat: allow configuration of operator pod labels

pkg/kube/object.go, pkg/kube/object_test.go, pkg/operator/workload/helper.go, pkg/vulnerabilityreport/testdata/fixture/pod.yaml, pkg/vulnerabilityreport/testdata/fixture/replicaset.yaml
skip replicaSet scanning when there is no active pod
- Related #387 
=> fix: skip replicaSet scanning when there is no active pod

deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml
Adds `priorityClassName` configuration property for the operator pod.
- Close #500
=> feat: allow configuration of operator pod priorityClassName

go.mod, go.sum
Fix vulnerability CVE-2022-27664
- Close #530 
-
=> fix: vulnerability CVE-2022-27664

pkg/plugins/trivy/model.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
add missing score column on vulnerability report
- Close #539 
=> add missing score column on vulnerability report

deploy/helm/templates/NOTES.txt, deploy/helm/templates/_helpers.tpl, deploy/helm/templates/config.yaml, deploy/helm/templates/deployment.yaml, deploy/helm/templates/leader_election.yaml, deploy/helm/templates/ns.yaml, deploy/helm/templates/policies.yaml, deploy/helm/templates/rbac.yaml, deploy/helm/templates/service.yaml, deploy/helm/templates/servicemonitor.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, docs/operator/installation/helm.md, hack/update-static.yaml.sh
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
Add functionality to create a namespace independent from the re…lease namespace. This useful, when using Trivy as dependency in another Helm chart
- Close #487 
=> feat: optional namespace

deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, docs/operator/configuration.md, docs/tutorials/private-registries.md, pkg/kube/secrets.go, pkg/operator/etc/config.go, pkg/vulnerabilityreport/controller.go
Added the ability to use secrets form namespaces rather than from imagePullSecrets to authenticate in private repositories. For example if there is no such secrets (imagePull) and credentials are "stored" in container runtime configuration.
New field - `privateRegistryScanSecretsNames` can be used to set namespaces and secret names. For example: `privateRegistryScanSecretsNames: {"default":"mysecret"}`
- Close #556 
=> Added ability to use secrets to scan private repo

deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, docs/index.md, pkg/metrics/collector.go, pkg/operator/etc/config.go
This is a proposition about feature request [562](https://github.com/aquasecurity/trivy-operator/issues/562).
Which permit to expose new metrics (enable by default but disabled via operator env variable) about CVE vulnerabilities find in VulnerabilityReports
- Close #562
=> Add metrics about CVE vulnerability ID

pkg/kube/secrets.go, pkg/kube/secrets_test.go, pkg/kube/testdata/fixture/sa_secret_same_domain.json, pkg/kube/testdata/fixture/sa_with_image_pull_secret_same_domain.json, pkg/kube/testdata/fixture/secret_same_domain.json
Then the values of the domains for docker registry in the pod imagePullSecret and service account imagePullSecret are the same, then in the final structure, the credentials from the secret specified in the Service Account will "overwrite" the values from the secret specified in the Pod specification.
I increase priority of the imagePullSecret from Pod priority. This coincides with the principle of how kubelet working with imagePullSecret.
- Close #575
=> feat: increase the priority of imagePullSecret from the pod spec

docs/tutorials/recommended_labels.rego
This is a trivial fix for the sample Rego file linked in the tutorial, [Writing Custom Configuration Audit Policies](https://aquasecurity.github.io/trivy-operator/v0.3.0/tutorials/writing-custom-configuration-audit-policies/).
This code contains an unnecessary hyphen in the package name, which when applied, prevents Configuration Audit from running.
The content is also different, but the package name which the Rego code embedded in the docs has are normal.
- Close #XXX
=> [fix] typo in sample rego for custom audit policy

deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml
Remove compliance report param from helm
- Close #621
=> chore: remove compliance report param from helm

pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
Add scanjob tmp folder on client/server mode
- Close #620
=> fix: add scanjob tmp folder on client/server mode

deploy/helm/Chart.yaml, deploy/helm/templates/config.yaml, deploy/helm/values.yaml
With this PR, we can set `trivy.gitHubToken`, `trivy.serverToken` and `trivy.serverCustomHeaders` within a secret defined outside of the chart, by using `trivy.existingSecret` value.
This is useful to avoid having those in plain text as values, notably for those who are using solutions like external-secrets for example.
- Close #638
- [n/a] I've added tests that prove my fix is effective or that my feature works.
- [n/a] I've included a "before" and "after" example to the description (if the PR is a user interface change).
=> feat(helm): allow users to define an external secrets for tokens

pkg/configauditreport/controller/controller.go, pkg/kube/object.go, pkg/policy/policy.go
re-generate config audit report following to cm change
- Close #642
=> fix: re-generate config audit report following to cm change

pkg/metrics/collector.go, pkg/metrics/collector_test.go, pkg/metrics/util.go, pkg/metrics/util_test.go
sanitize k8s metrics labels
- Close #646
=> fix: sanitize k8s metrics labels

pkg/kube/object.go
In this change we have added the service kind of resources to be evaluated againt rego policies for service kinds and hence be able to create reports for service type of resources as well
Adding Service Kind For ConfigAuditReports
=> Adding Service Kind For ConfigAuditReports

build/trivy-operator/Dockerfile
specify user numerically in Dockerfile
Simple change to Dockerfile so that the user is specified numerically.  This allows container orchestrators to know the container will run as non-root without inspecting the passwd file in the image (which most of them can't/won't do).
- Close #573
=> fix Dockerfile to use numeric user

pkg/operator/operator.go
Disable ingress caching by client
- Close #654
=> fix: disable ingress caching by client

deploy/helm/templates/config.yaml, deploy/helm/values.yaml, docs/operator/configuration.md, pkg/configauditreport/controller/controller.go, pkg/trivyoperator/config.go
Record only failed checks on misconfiguration reports
- Close #495 
=> feat: record misconfig failed checks only

deploy/helm/templates/config.yaml, deploy/helm/values.yaml, docs/operator/configuration.md, go.mod, go.sum, pkg/configauditreport/controller/controller.go, pkg/operator/workload/helper.go, pkg/trivyoperator/config.go, pkg/vulnerabilityreport/controller.go
Skip workload scanning by resource label)
- Close #585
=> feat: skip workload scanning by resource label

deploy/helm/templates/config.yaml, deploy/helm/values.yaml
The value that controls the creation of the trivy-operator-trivy-config secret was wrong. This fixes it.
After review, I moved the value from the trivy to the operator section, without readdressing it in the config.yaml file
This aims at fixing this.
[Gist: Helm rendered with defaults](https://gist.github.com/cebidhem/378ea3d9ee6e7e23f1d7737716ab4a90)
[Gist: Helm rendered with existing secret](https://gist.github.com/cebidhem/ecb461be3f0588e71b7fd5778e03a0a3)
- Close #690 
- [-] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [-] I've added usage information (if the PR introduces new options)
- [-] I've included a "before" and "after" example to …
=> fix(helm): fixes the install failure when using an existing trivy-operator-trivy-config secret

docs/integrations/metrics.md, pkg/metrics/collector.go, pkg/metrics/collector_test.go
Add Installed Version and Resource from vulnerability report to vulnerability id metrics.
Example:
```
trivy_vulnerability_id{image_digest="",image_registry="index.docker.io",image_repository="kindest/local-path-provisioner",image_tag="v0.0.22-kind.0",installed_version="1.1.1n-0+deb11u1",name="replicaset-944577769",namespace="local-path-storage",resource="libssl1.1",severity="Critical",vuln_id="CVE-2022-2068"} 1
```
- Close #645
=> Add installed version and resource to trivy_vulnerability_id metrics

deploy/helm/templates/config.yaml
Signed-off-by: cebidhem <cebidhem@pm.me>
As described in the issue, a regression has been introduced. This aims at aligning the config with the values for using an existingSecret.
- Close #715 
- [-] I've added tests that prove my fix is effective or that my feature works.
- [-] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [-] I've added usage information (if the PR introduces new options)
- [-] I've included a "before" and "after" example to the description (if the PR is a user interface change).
=> fix(helm): Aligns config with the values for the existingSecret value

deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, docs/operator/configuration.md, pkg/trivyoperator/config.go
record misconfig failed checks only enable by default
- Related #495
=> feat: record misconfig failed checks only enable by default

pkg/operator/operator.go, pkg/trivyoperator/config.go, pkg/vulnerabilityreport/controller/helper.go, pkg/vulnerabilityreport/controller/scanjob.go, pkg/vulnerabilityreport/controller/workload.go, pkg/vulnerabilityreport/suite_test.go
separate scan job with different reconciler
- Close #725
=> refactor: separate scan job with different reconciler

pkg/configauditreport/controller/helper.go, pkg/configauditreport/controller/policyconfig.go, pkg/configauditreport/controller/resource.go, pkg/operator/operator.go
refactor: separate policy config with different reconciler
- Close #726
=> refactor: separate policy config with different reconciler

pkg/policy/policy.go
In this change we are setting the kubernetes scanner for rolebinding and clusterrolebinding resources. The rbac scanner is to be used for roles and clusterroles.
=> Bugfix - Changing scanner type for RoleBindings and ClusterRoleBindings

docs/getting-started/installation/helm.md
Signed-off-by: ollide <hg.otothel@gmail.com>
Adds the `clustercompliancereports.aquasecurity.github.io` CRD in the Helm Uninstall documentation.
The upgrade doc suggests to uninstall the previous version before installing the latest version. Coming from 0.4.0, I followed the Helm Uninstall doc, but the installation of 0.10.1 failed, because `helm.md` was missing the clustercompliancereports CRD.
See also #795, where another user had the same problem.
=> docs: add clustercompliancereports crd in Helm uninstall section

deploy/specs/cis-1.23.yaml, deploy/specs/nsa-1.0.yaml
The specs for the ClusterComplianceReports of nsa and cis (https://github.com/aquasecurity/trivy-operator/tree/main/deploy/specs) currently contain empty `checks`, which should be an array and not null (from my understanding of the current CRD, feel free to correct me).
- Close #881
=> fix: remove null checks in clustercompliancereports

pkg/apis/aquasecurity/v1alpha1/common_types.go, pkg/configauditreport/controller/helper.go, pkg/configauditreport/controller/nodecollector.go, pkg/configauditreport/controller/policyconfig.go, pkg/configauditreport/controller/resource.go, pkg/operator/envtest/controller_test.go, pkg/operator/envtest/suite_test.go, pkg/operator/envtest/testdata/fixture/config-audit-ttl-historical.yaml, pkg/operator/envtest/testdata/fixture/config-audit-ttl.yaml, pkg/operator/envtest/testdata/fixture/policy.yaml, pkg/operator/envtest/testdata/fixture/vulnerability-ttl.yaml, pkg/operator/operator.go, pkg/operator/ttl_report.go, pkg/operator/workload/helper.go, pkg/policy/policy.go, pkg/policy/policy_test.go
check if re-scan required for mis-config reports on ttl
- Close #884
=> fix: check if re-scan required for misconfig reports

deploy/helm/templates/config.yaml
encode trivy token on built-in server
- Close #897 
=> chore: encode trivy token built-in server

deploy/specs/cis-1.23.yaml
kubelet wrong check mapping
- Related #815
=> chore: kubelet wrong check mapping

pkg/operator/operator.go, pkg/operator/ttl_report.go
Disable config-audit scanner cause operator to crash
- Close #930
=> fix: disable config-audit scanner cause operator to crash

deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, pkg/plugins/trivy/flags.go, pkg/plugins/trivy/flags_test.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, tests/e2e/client-server/workload/00-assert.yaml, tests/e2e/fs-mode/workload/00-assert.yaml, tests/e2e/image-mode/workload/00-assert.yaml
trivy-v0.37.x deprecate flag support
- Close #948
- Close #942
=> fix: trivy-v0.37.x deprecate flags support

docs/docs/crds/exposedsecret-report.md, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/plugins/trivy/testdata/fixture/exposedsecret_report.json, pkg/plugins/trivy/testdata/fixture/full_report.json
- properly populate the target attribute of exposed secrets
- update docs
Before:
```yaml
secrets:
- category: Stripe
match: 'publishable_key: *****'
ruleID: stripe-access-token
severity: HIGH
target: ""
title: Stripe
- category: Stripe
match: 'secret_key: *****'
ruleID: stripe-access-token
severity: HIGH
target: ""
title: Stripe
```
After:
```yaml
secrets:
- category: Stripe
match: 'publishable_key: *****'
ruleID: stripe-access-token
severity: HIGH
target: "/app/config/secret.yaml"
title: Stripe
- category: Stripe
match: 'secret_key: *****'
ruleID: stripe-access-token
severity: HIGH
target: "/app/config/secret.yaml"
title: Stripe
```
- Close #992
=> properly populate the target attribute of exposed secrets

deploy/helm/templates/config.yaml, deploy/static/trivy-operator.yaml
The values for `trivy.resources` were not quoted.
If the Helm value is a string containing only a number, e.g. `trivy.resources.requests.cpu: "2"`, the generated YAML for the config map is `trivy.resources.requests.cpu: 2`, which is of the type number, not string, which is not a valid value for a Kubernetes config map.
Adding the `| quote` filter should fix this bug.
=> fix!: Helm chart: add missing quote filter in config template

pkg/configauditreport/controller/node.go
re-queue nodes reconciliation non-ready status
- Close #1021
=> fix: requeue  non-ready nodes

pkg/plugins/trivy/plugin.go
=> TRIVY_INSECURE never set in ClientServer FS mode

pkg/operator/envtest/testdata/fixture/config-audit-ttl-historical.yaml, pkg/operator/envtest/testdata/fixture/vulnerability-ttl.yaml, pkg/operator/ttl_report.go
=> incorrect check of ttlReportAnnotationStr in TTLReportReconciler

pkg/kube/secrets.go, pkg/kube/secrets_test.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/vulnerabilityreport/controller/workload.go
This change is fixing the authentication issues when accessing private registries using mirroring. The focus here is the mirror image mapping should happen before the credentials and AWS region are discovered.
Looking into the code, currently the credentials are being mapped per container at workload level in the `submitScanJob` function [here](https://github.com/aquasecurity/trivy-operator/blob/v0.12.1/pkg/vulnerabilityreport/controller/workload.go#L224-L238), however the mirror mapping is only happening afterwards at plugin `GetScanJobSpec` level [here](https://github.com/aquasecurity/trivy-operator/blob/v0.12.1/pkg/plugins/trivy/plugin.go#L847), so the credential is being mapped for the original registry server instead of the target mirrored repository. In my humble opinion this logic …
=> fix: fixing auth issues when accessing private registries using mirroring

pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
Updates the `VulnerabilityReport`'s `Score` field logic to prefer NVD score if both NVD and Vendor V3 CVSS scores exist, using Vendor score as fallback in case no NVD score is available.
- Close #1079
=> prefer nvd score if both nvd and vendor cvss v3 scores exist

.github/workflows/build.yaml, .github/workflows/chart-testing.yaml, .github/workflows/private-registries.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/release.yaml, go.mod
fix Golang runtime CVEs
- Close #1171
=> chore: bump golang version 1.20.3

deploy/helm/templates/config.yaml
Disabling vulnerability plugin crash operator
- Close #1165
=> fix: disable vuln-plugin crash-operator

deploy/helm/templates/trivy-server.yaml
It is sometimes essential defining tolerations. There's a `nodeSelector` field but no tolerations settings. For us it is causing pod to be in a "Pending" state.
Is still not opened, seems like simple fix.
=> fix: Add tolerations to trivy-server template

pkg/docker/config.go, pkg/docker/config_test.go, pkg/kube/secrets.go, pkg/kube/secrets_test.go
Now pods `imagePullSecrets` with secret type `kubernetes.io/dockercfg` are ignored when generating `imagePullSecrets` for scan jobs. This PR adds functionality to treat legacy `kubernetes.io/dockercfg` secrets and converts them to newer version (`kubernetes.io/dockerconfigjson`) for operator scan jobs.
I think it's not too bad to support the old types of secrets since both types (`kubernetes.io/dockerconfigjson` and `kubernetes.io/dockercfg`) perform the same function and are still supported by kubernetes.
If you don't think so - could you please explain why we can't support both types of secrets in the operator?
=> feat: Add support fo legacy dockercfg in scan jobs

pkg/kube/resources.go, pkg/kube/resources_test.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/vulnerabilityreport/controller/scanjob.go, pkg/vulnerabilityreport/controller/workload.go
This change is fixing the mismatch between the real and stored pod spec hash when using image mirroring, this issue was introduced in #1066 when the original container image is modified and stored in the runtime cache.
- Close #1204
=> fix: pod spec hash issues when using image mirroring

deploy/helm/templates/trivy-server.yaml
Explicitly specify the kind and apiVersion for the volumeClaimTemplates of trivy-server
- Close #1206
=> fix: specify trivy-server persistent volume claim for argocd sync

go.mod, go.sum, pkg/policy/policy_test.go
=> chore: bump defsec v0.89.0

pkg/kube/logs.go
vulnerabilities report not created after k8s v1.27.x due to controller label has been change 
- Close #1194
=> fix: vulnerabilities report not created after k8s v1.27.x

.goreleaser.yaml
cosign needs the `--yes` parameter when running as a script. This
specifies it to fix the signing steps.
- Close #XXX
=> fix: specify confirmation in cosign invocation

pkg/configauditreport/builder.go, pkg/configauditreport/builder_test.go, pkg/rbacassessment/builder.go, pkg/rbacassessment/builder_test.go
When rbac resources is having capital letter in its name then trivy-operator throws error for creating its configaudit report OR rbac report. 
This happens bcoz capital letter name is not allowed in majority of the resources except rbac. 
To resolve this, we will make sure that trivy-operator doesnot try create report with capital letter, if capital letter comes then we generate report with hashvalue name
- replace IsValidLabelValue to IsDNS1123Label which allows only lower case value and other similar constraint on length
resolve: #343
=> bugfix: rbac resource with capital letter name

pkg/metrics/collector.go
Currently the metric `trivy_vulerability_id` will only be created once per image and CVE, even if the CVE occurs in multiple packages/libs.
With the changes in this PR, there will be one `trivy_vulnerability_id` metric for each occurence in an image (see example below).
```
$ kubectl version --short
Client Version: v1.27.2
Server Version: v1.26.4+k3s1
$ helm upgrade --install external-dns external-dns/external-dns --set image.tag=v0.12.0
Release "external-dns" does not exist. Installing it now.
NAME: external-dns
LAST DEPLOYED: Thu Jul  6 22:41:52 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
***********************************************************************
* External DNS                                                        * …
```
=> feat: create "trivy_vulerability_id" metric for each occurence

pkg/configauditreport/controller/helper.go, pkg/configauditreport/controller/policyconfig.go, pkg/configauditreport/controller/resource.go, pkg/operator/operator.go, pkg/plugins/trivy/plugin.go, pkg/policy/policy.go, pkg/policy/policy_test.go
outdated-api last applied resource support
- Close #1345
=> fix: outdated-api last applied resource support

deploy/helm/README.md, deploy/helm/values.yaml, pkg/operator/etc/config.go
sbom generation enable by default
- Related #143
=> fix: sbom generation enable by default

cmd/trivy-operator/main.go, go.mod, go.sum
Added automaxprocs package to automatically set the env var `GOMAXPROCS`, which will improve the performance of the trivy-operator when running on large clusters.
- Close #1360
=> feat: add automaxprocs to automatically set GOMAXPROCS

deploy/helm/crds/aquasecurity.github.io_sbomreports.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/sbom-report.md, pkg/apis/aquasecurity/v1alpha1/sbom_types.go, pkg/plugins/trivy/util.go
> The type of the SpecVersion field in the CycloneDX SBOM is `string` .
> 
> https://cyclonedx.org/docs/1.4/json/#specVersion
This Pull Request changes the SpecVersion field of the SBOM to a `string`.
- Close #1377
=> fix: sbomReport: wrong type of SpecVersion field

deploy/helm/templates/deployment.yaml
Addresses issue where setting helm value `operator.sbomGenerationEnabled=false` does not disable SBOM generation.
- Close #1381
=> fix: helm sets wrong value for OPERATOR_SBOM_GENERATION_ENABLED

docs/tutorials/integrations/webhook.md
Webhook integration already supports SBOM Report.
https://github.com/aquasecurity/trivy-operator/blob/0496b2c75988ef93c47e849a973a2809dadc08bf/pkg/webhook/webhookreporter.go#L56
=> docs: add SBOM Report for webhook integrations

deploy/helm/templates/servicemonitor.yaml, deploy/helm/values.yaml
Adds a capabilities check to the `ServiceMonitor` template to make sure that the K8s cluster does have the prometheus monitoring stack installed. If not, deploy will silently ignore the resource even if enabled.
None.
=> fix(chart): only create servicemonitor if API supports it

deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml
You may want to clean up old replicasets so that these don't appear in metrics, OPA violations, ArgoCD UI and so on.
Therefore you want to overwrite the Kubernetes default revision history limit.
See [Kubernetes Clean up Policy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy).
=> feat: allow changing the default revisionHistoryLimit

pkg/plugins/trivy/plugin.go
add insecure flag for scanning container
- Close #1414
=> fix: add insecure flag for scanning container

deploy/helm/README.md, deploy/helm/templates/servicemonitor.yaml, deploy/helm/values.yaml
The PR explicitly declares missing and commented properties used by the chart with empty or default values.
The PR includes minor README changes rendered by helm-docs run.
The PR does not change any functionality of the chart.
=> chore: declare missing properties in values.yaml

pkg/operator/ttl_report.go
the purpose of this change is for the TTL reconcile to respect scanners(vulns, exposed-secret and etc) enabled flags 
- [x ] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
=> fix: report ttl respect scanner flags

deploy/helm/README.md, deploy/helm/templates/config.yaml, deploy/helm/values.yaml, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
=> feat: skip db update for clientserver mode

deploy/helm/templates/_helpers.tpl, deploy/helm/templates/config.yaml, deploy/helm/templates/deployment.yaml, deploy/helm/templates/leader-election.yaml, deploy/helm/templates/ns.yaml, deploy/helm/templates/rbac.yaml, deploy/helm/templates/service.yaml, deploy/helm/templates/servicemonitor.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/helm/templates/trivy-server.yaml, deploy/static/trivy-operator.yaml
The PR reformats chart templates to common style with more readable blocks and indents.
ConfigMap `trivy-operator-policies-config` has been deleted, because it does not have any data.
The PR does not change any functionality of the chart.
Similar PRs: https://github.com/apache/airflow/pull/29917 https://github.com/apache/airflow/pull/29941 https://github.com/apache/airflow/pull/30312 https://github.com/minio/minio/pull/16947 https://github.com/apache/superset/pull/23681
The following command prints same (minor differences) output before and after changes:
```sh
helm template test deploy/helm
```
=> chore: reformat chart templates

docs/docs/configuration-auditing/built-in-policies.md
This is based on the following Slack questions: https://aquasecurity.slack.com/archives/C03L2H45L3H/p1692294989987299?thread_ts=1692293975.132919&cid=C03L2H45L3H
=> docs: adding information on cis benchmarks and config audit scans

pkg/plugins/trivy/plugin.go
Add image digest to report
- Close #1393
=> fix: add image digest to report

deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/servicemonitor.yaml, deploy/helm/values.yaml
- Allows setting `annotations` to the ServiceMonitor resource. Useful for things like https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
- Allows setting `endpointAdditionalProperties` such as `relabeling`, `metricRelabelings` etc.
=> feat: Add additional values for ServiceMonitor in helm chart

deploy/helm/templates/config.yaml, deploy/helm/templates/servicemonitor.yaml
The PR reformats chart templates missed in the PR https://github.com/aquasecurity/trivy-operator/pull/1439 and fixes formatting introduced in the PR https://github.com/aquasecurity/trivy-operator/pull/1452.
The PR does not change any functionality of the chart.
- https://github.com/aquasecurity/trivy-operator/pull/1439
- https://github.com/aquasecurity/trivy-operator/pull/1452
=> chore: reformat missed chart templates

deploy/helm/README.md, deploy/helm/templates/trivy-server.yaml, deploy/helm/values.yaml
Added a new config value under `trivy.storageClassEnabled`.
In it's very simplistic implementation:
- value is `true`: Helm chart is rendered with `kind: PersistentVolumeClaim` as `data` volume.  
- value is `false`: Will *not* render `kind: PersistentVolumeClaim`, but configure a volume `data` as `emptyDir` instead.
> This setting is left `true` by default, avoiding any existing compatibility issues.
- Close #1456
=> ability to opt-out persistent volume claim for trivy-server

deploy/helm/crds/aquasecurity.github.io_vulnerabilityreports.yaml, deploy/static/trivy-operator.yaml, pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go
I built a custom operator (https://github.com/telekom-mms/trivy-dojo-report-operator) that uses the kopf-operator (github.com/nolar/kopf/) framework. This framework can act on kubernetes-resource creation. To detect which resources were already worked on, kopf adds a the last state of the resource as an annotation or status to the resource.I cannot use the annotation-feature, because of this issue: https://github.com/kubernetes-sigs/kubebuilder/issues/2556 (annotations get too long).
So my proposal is to preserve unknown fields in the vulnerabilityreport-crd. This way I can add a status-field which kopf then can use to store the state.
=> add: preserve unknown fields in vulnerabilityreport

deploy/helm/templates/trivy-server.yaml
To improve the monitoring of containers in our environment. It would be helpful if the trivy-server container had a clearer name. The current name `main` can be confusing.
=> feat: use serverServiceName as container name

deploy/helm/README.md, deploy/helm/templates/trivy-server.yaml, deploy/helm/values.yaml
Makes trivy-server replicas configurable.
- Close #1321 
=> feat: make trivy-server replicas configurable

deploy/helm/templates/config.yaml
While starting the builtInTrivyServer the following log message is being displayed:
```
'TRIVY_SKIP_UPDATE' is deprecated. Use 'TRIVY_SKIP_DB_UPDATE' instead.
```
This PR will update the configured environment variable.
=> feat: use TRIVY_SKIP_DB_UPDATE env variable

pkg/plugins/trivy/plugin.go
disable compressed logs break trivy command
- Close #1504
=> fix: disable compressed logs break trivy command

deploy/helm/README.md, deploy/helm/templates/_helpers.tpl, deploy/helm/templates/configmaps/operator.yaml, deploy/helm/templates/configmaps/trivy.yaml, deploy/helm/templates/deployment.yaml, deploy/helm/templates/trivy-server/statefulset.yaml, deploy/helm/values.yaml
This PR provides a single global value to set the `image.registry` values used multiple times inside the chart. This makes it easier to change the `image.registry` across all values without inconsistencies. 
Also, global values are accessible by parent and sub-charts, which makes it easier to handle in multi-chart environments.
These change only affects Helm deployments, it does not modify any Trivy Operator components.
=> feat: Implement global chart values for image.registry

deploy/static/components/metrics/kustomization.yaml, deploy/static/components/metrics/metrics.yaml
In order to provide "feature parity" with the chart, a component is proposed to expose the ServiceMonitor manifest. It can be consumed by anyone using a remote component or by downloading it and using it locally like the original chart.
About the checklist, let me know what you would like for this, and I'll adjust the PR accordingly.
=> feat(manifests): add metrics component for static installation

deploy/helm/templates/monitor/service.yaml, deploy/helm/values.yaml
Add headless monitor service configurable
- [] I've added tests that prove my fix is effective or that my feature works.
For a better usability of the helm chart it may be useful to make the headless service configurable. This is just relevant if you want to export the metrics and scrape them with prometheus.
With this configuration flag, it is not necessary anymore to adjust the service deployment by hand.
=> feat: make headless service configurable

docs/tutorials/private-registries.md
The tutorial states you need to use `command: fs` while it earlier also states it needs to be filesystem. 
the value `fs` won't work.
- Close #XXX
=> docs: change command value fs to filesystem in private-registries tutorial

pkg/plugins/trivy/image.go
Scan pods can't pull images from ECR when AWS_REGION variable not set.
Added AWS_REGION environment variable for Amazon Elastic Container Registry images in the ClientServer mode
=> feat: Added AWS_REGION env for ECR images in the ClientServer mode

pkg/plugins/trivy/image.go
This will allow  `trivy.dbRepositoryInsecure: "true"` setting to work also in ClienServer mode. Useful for javaDbRepository which is (AFAIK) not stored on Server
- Close #1590
=> fix: handle trivy insecure database in ClientServer mode

README.md, docs/index.md
This is how it's done in Trivy and Tracee
https://github.com/aquasecurity/trivy
https://github.com/aquasecurity/tracee
=> docs: modify README and docs landing page to reflect the same content

deploy/helm/README.md, deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, pkg/operator/etc/config.go, pkg/operator/ttl_report.go, pkg/vulnerabilityreport/controller/helper.go, pkg/vulnerabilityreport/controller/scanjob.go, pkg/vulnerabilityreport/controller/workload.go
missing reports on via cluster sbom cache
- Close #1697
=> fix: missing reports on via cluster sbom cache

go.mod, go.sum, pkg/configauditreport/controller/node.go
fix: hang node collector node shutdown
- Close #1660
- Related https://github.com/aquasecurity/trivy-kubernetes/pull/273
=> fix: hang node collector node shutdown

go.mod, go.sum
Fix CVE-2023-49568
- Close #1722
=> sec: fix CVE-2023-49568

pkg/configauditreport/controller/resource.go, pkg/kube/object.go
ingress resource on config-scan support
- Close #1703
=> feat: ingress resource on config-scan support

pkg/metrics/collector.go
fix: service monitor cause operator to crash
- Close #1682
=> fix: service monitor cause operator to crash

deploy/helm/README.md, deploy/helm/templates/configmaps/trivy.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, pkg/plugins/trivy/config.go, pkg/plugins/trivy/config_test.go, pkg/plugins/trivy/filesystem.go, pkg/plugins/trivy/image.go
Retrieve sbom specified sources from oci registries
- Close #1624
=> feat: retrieve sbom specified sources from oci registries

deploy/helm/templates/configmaps/trivy.yaml
cve list might be provided as list:
trivy {
ignoreFile = ["CVE-1970-0001", "CVE-2023-49568"]
}
result in configmap:
trivy.ignoreFile: |
CVE-1970-0001
CVE-2023-49568
=> fix: Update trivy.yaml to support cve list

pkg/operator/envtest/suite_test.go, pkg/operator/operator.go, pkg/plugins/factory.go, pkg/trivyoperator/config.go, pkg/trivyoperator/config_test.go
fix: set audit config plugin trivy by default
- Close #1738
=> fix: set audit config plugin trivy by default

docs/docs/vulnerability-scanning/managed-registries.md
Updated the documentation about accessing ACR with workload identities
Recently I had to add the trivy operator to our cluster on AKS, so I've updated the relevant documentation for Microsoft Entra workload identities.
None since it's a trivial contribution
=> docs: updated managed registries on Azure with Workload Identities

deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/trivy-server/statefulset.yaml, deploy/helm/values.yaml
Allows the configuration of the PVC size for the trivy-server. In our environment we had a full disk.
=> feat: allow configration of trivy-server pvc size

deploy/helm/README.md, deploy/helm/templates/trivy-server/statefulset.yaml, deploy/helm/values.yaml
Added the possibility to add additional annotations to the trivy-server pod.
Useful for istio for example.
- Close #1820
=> feat: added config for additional server annotations

.github/workflows/release-snapshot.yaml
chore: use light goreleaser for snapshot releases
=> chore: use light goreleaser for snapshot releases

docs/docs/configuration-auditing/built-in-policies.md
As mentioned in #1778 the `cis-benchmark` policies are no longer part of the [defsec repository](https://github.com/aquasecurity/defsec/) and have been migrated to the new [trivy-policies repository](https://github.com/aquasecurity/trivy-policies) in https://github.com/aquasecurity/defsec/pull/1460.
This PR updates the links and wording.
=> docs: Change broken link from defsec to trivy-policies

deploy/helm/README.md, deploy/helm/templates/configmaps/trivy-operator-config.yaml, deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, docs/getting-started/installation/configuration.md
This feature / change enables providing Configuration for the Trivy-Operator from custom ConfigMap and/or Secret using the Helm Chart, which is a common / widely used pattern.
So far, all configuration have been passed using the `env` field in the [deployment](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/deployment.yaml#L46-L129).
Since this method has the [highest precedence](https://renehernandez.io/notes/env-vars-precedence-k8s-pod/), it was not possible to provide additional values.
To overcome this, all `.Values.operator.*` Helm values have been moved into their own ConfigMap called `trivy-operator-config` and then referred to it with `envFrom`.
This allowes to provide additional ConfigMaps/Secrets and override previous values.
The behaviour is …
=> feat: Enable passing values for operator through custom ConfigMap and/or Secrets

pkg/plugins/trivy/image.go, pkg/plugins/trivy/image_test.go, pkg/plugins/trivy/jobspec.go
The PR fixes regex for gcr images and should fix the issue https://github.com/aquasecurity/trivy-operator/issues/1868.
Tested by the following code:
```go
package main
import (
"fmt"
"regexp"
)
const (
GCPCR_Image_Regex = `^(us\.|eu\.|asia\.)?gcr\.io.*|^([a-zA-Z0-9-]+)-*-*.docker\.pkg\.dev.*`
//GCPCR_Image_Regex = `^(gcr\.io.*|^([a-zA-Z0-9-]+)-*-*.docker.pkg.dev.*)`
)
func main() {
imageRegex := regexp.MustCompile(GCPCR_Image_Regex)
global := imageRegex.MatchString("gcr.io/company/application")
fmt.Println("global", global)
us := imageRegex.MatchString("us.gcr.io/company/application")
fmt.Println("us", us)
eu := imageRegex.MatchString("eu.gcr.io/company/application")
fmt.Println("eu", eu)
asia := imageRegex.MatchString("asia.gcr.io/company/application")
fmt.Println("asia ", asia)
docker …
```
=> fix: access to private regional gcr

deploy/helm/README.md, deploy/helm/templates/deployment.yaml, deploy/helm/templates/trivy-server/statefulset.yaml, deploy/helm/values.yaml
Sometimes we may face situations where we need to be able to identify a deployment owner inside a cluster, this is easily done with labels, but the current trivy-operator chart does not allow to set custom labels to the controllers, only the pods'.
This PR introduces new `operator.labels` and `trivy.labels` values that will let users add custom labels to the operator and trivy-server controllers.
=> feat: add extra labels for operator and server controllers in Helm chart

deploy/helm/README.md, deploy/helm/templates/monitor/service.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml
I'm not sure about the default value `TCP`. I think thats the Kubernetes default but not sure if trivy has something specific.
- Close #1866
=> feat: added configurable appProtocol to metrics service

.github/workflows/publish-helm-chart.yaml, README.md, docs/getting-started/installation/helm.md, docs/index.md, docs/tutorials/grafana-dashboard.md
See linked issue:
> The helm chart of trivy-operator is published using the classic approach with a static webserver and an index.yaml (on a separate Repository https://github.com/aquasecurity/helm-charts).
> 
> ```bash
> $ helm repo add aqua https://aquasecurity.github.io/helm-charts/
> $ helm install trivy-operator aqua/trivy-operator \
>      --namespace trivy-system \
>      --create-namespace \
>      --version 0.20.6
> ```
> 
> In helm 3.8+ the OCI method went GA:
> - https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html?m=1
> - https://helm.sh/docs/topics/registries/
> - https://github.com/helm/helm/releases/tag/v3.8.0
> 
> I'd like to see you pushing the packaged helm chart(s) also on ghcr.io, alongside the container images and trivy-db's.
> …
=> feat: Also publish chart to OCI registry

deploy/helm/templates/trivy-server/statefulset.yaml, pkg/plugins/trivy/filesystem.go, pkg/plugins/trivy/image.go
ssl-cert dir support on init containers and built-in server
- Close #1676
=> feat: ssl-cert dir support on init containers and built-in server

deploy/helm/README.md, deploy/helm/values.yaml, docs/docs/crds/clustervulnerability-report.md
From the documentation and the description of helm values it's not obvious that SBOM generation is required to enable ClusterVulnerabilityReports. @chen-keinan told me about that in discussion #1898. I proposed an adjustment of the documentation for this part.
- resolves #1898
=> docs: Improve documentation for ClusterVulnerabilityReports

pkg/kube/resources.go, pkg/kube/resources_test.go, pkg/vulnerabilityreport/controller/scanjob.go
generate scan reports for individual completed containers when pod scan failed
- Close #1901
=> fix: generate scan reports for individual completed containers when pod scan failed

pkg/operator/operator.go
fix: load trivy-policies by config
- Related #1897
=> fix: load trivy-policies by config

CONTRIBUTING.md, README.md, RELEASING.md, deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/configmaps/trivy.yaml, deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml, deploy/static/namespace.yaml, deploy/static/trivy-operator.yaml, docs/docs/crds/clustercompliance-report.md, docs/docs/crds/configaudit-report.md, docs/docs/crds/exposedsecret-report.md, docs/docs/crds/rbacassessment-report.md, docs/docs/design/caching_scan_results_by_repo_digest.md, docs/docs/design/design_compliance_report.md, docs/docs/design/design_starboard_at_scale.excalidraw, docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/docs/design/ttl_scans.md, docs/index.md, docs/tutorials/private-registries.md, itest/helper/helper.go, mkdocs.yml
=> release: prepare v0.19.1

deploy/helm/README.md, deploy/helm/templates/monitor/service.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml
My use case is to scrape the metrics from a prometheus outside the Kubernetes cluster, thus I use a Service of kind NodePort for this.
=> feat: Helm, allow to define service type for metrics Service

cmd/trivy-operator/main.go
Initialize logging early in the main() function to ensure logger is configured before any other part of the code tries to log messages, including any package-level variables or init() functions that might trigger logging.
- Close #1934
=> fix: Controller-runtime Logger Fails to Initialize

pkg/vulnerabilityreport/controller/scanjob.go
Add appropriate info msg for not supported windows images
- Close #1953
=> fix: add appropriate info msg for not supported windows images

go.mod, go.sum
Handle non sha256 digest
- Close #1920
=> fix: handle non sha256 digest

pkg/operator/operator.go
Configure context timeout for sync resources
- Close #1932
=> fix: configure context timeout for sync resources

pkg/operator/operator.go
Remove controller manager timeout
- Close #1979
=> fix: remove controller manager timeout

deploy/helm/templates/configmaps/trivy.yaml
This PR fixes the typo introduced in commit https://github.com/aquasecurity/trivy-operator/commit/f652926cc222efe7377c44389c38432551f1f356#diff-fcb9b9ad942468c142ea99160a28f7b76079583996e888e9801bce4f0f104784R98 that impacts the usage of Trivy Operator in Client/Server mode.
Like mentioned in the issue though, it looks like the commit that introduced the issue was done by a CI/CD process ?
- Close [1983](https://github.com/aquasecurity/trivy-operator/issues/1983)
=> fix(helm): trivy server value typo

docs/docs/vulnerability-scanning/trivy.md
Update client/server mode documentations
=> docs: add information on running Helm Chart in client server mode

go.mod, go.sum
- Close https://github.com/aquasecurity/trivy-operator/issues/2022
go-getter is vulnerable to argument injection. This update closes that.
=> sec: update go-getter to latest version

pkg/policy/loader.go
I fixed an incorrect message displayed when downloading policy data fails.
=> fix: typo in policy download

deploy/helm/templates/specs/cis-1.23.yaml, deploy/helm/templates/specs/nsa-1.0.yaml, deploy/helm/templates/specs/pss-baseline.yaml, deploy/helm/templates/specs/pss-restricted.yaml
Only deploy ClusterComplianceReports (using Helm) if they are enabled.
- As discussed in #1078
=> feat(helm): only deploy ClusterComplianceReports if enabled

pkg/plugins/trivy/config.go
Regarding the issue in #2063, I checked the code and realized that environment value (TRIVY_USER/TRIVY_PASSWORD) is not set at initContainer step.
So I looked at the related code, and it seemed to be caused by the DB Registry User/Password information set in k8s secret being set to refer to ConfigMap data.
```
func (c Config) TrivyDBRepositoryCredentialsSet() bool {
_, userOk := c.Data[keyTrivyDBRepositoryUsername]
_, passOk := c.Data[keyTrivyDBRepositoryPassword]
return userOk && passOk
}
```
I tried putting the trivy db private registry credentials in the configmap and it worked fine, but I think it should be referencing secret as originally intended, please confirm
- Close #2063
=> fix: trivy db repository credential set

deploy/helm/README.md, deploy/helm/templates/configmaps/trivy.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, pkg/configauditreport/plugin.go, pkg/plugins/trivy/config.go, pkg/policy/policy.go, pkg/policy/policy_test.go
The use of embedded checks, fallback for air-gapped env.
- Close #2078
=> fix: the use of embedded checks, fallback for air-gapped env.

deploy/helm/README.md, deploy/helm/templates/configmaps/operator.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml, pkg/operator/operator.go, pkg/trivyoperator/config.go
support policies bundle insecure download
- Close #2099
=> fix: policies bundle insecure

.gitignore, pkg/vulnerabilityreport/controller/scanjob.go
non completed containers with invalid stacktrace
- Close #2101
=> fix: non completed containers with invalid stacktrace

deploy/helm/README.md, deploy/helm/values.yaml, pkg/vulnerabilityreport/builder.go, pkg/vulnerabilityreport/builder_test.go
The `scanJobAnnotations` were only added to the `Pod`, and not the `Job`, despite the name. Let's add the annotations to both places.
- Close #2109
=> fix: Add scanJobAnnotations to the Job instead of just the Pod

pkg/policy/loader.go
failed to eval rego misconfig policy
- Close #2123
=> fix: failed to eval rego misconfig policy

deploy/helm/README.md, deploy/helm/values.yaml, pkg/trivyoperator/config.go
update olm defaults
- Close #2134
=> fix: update olm defaults

deploy/helm/README.md, deploy/helm/templates/configmaps/policies.yaml, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml
make operator policies-config optional
- Close #2098
=> chore: make operator policies-config optional

docs/tutorials/grafana-dashboard.md
Adding section on how to import the dashboard using the Grafana Helm Chart. I think this is helpful as many use the Grafana Helm chart to set it up. 
From the Grafana spec:
https://github.com/grafana/helm-charts/blob/grafana-8.0.2/charts/grafana/values.yaml#L708-L759
=> docs: add section on importing the Grafana dashboard using the Grafana Helm Chart

go.mod, go.sum
```
ghcr.io/aquasecurity/trivy-operator:5d266cfb4c9b643446c2262160c5d5f04b95f651-amd64 (alpine 3.19.1)
==================================================================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
usr/local/bin/trivy-operator (gobinary)
=======================================
Total: 1 (HIGH: 1, CRITICAL: 0)
┌────────────────────────────────┬───────────────┬──────────┬────────┬───────────────────┬───────────────┬──────────────────────────────────────────────────────────┐
│            Library             │ Vulnerability │ Severity │ Status │ Installed Version │ Fixed Version │                          Title                           │
├────────────────────────────────┼───────────────┼──────────┼────────┼───────────────────┼───────────────┼──────────────── …
```
=> chore: bump github.com/hashicorp/go-getter-v1.7.5

deploy/helm/templates/specs/eks-cis-1.4.yaml, deploy/helm/templates/specs/k8s-cis-1.23.yaml, deploy/helm/templates/specs/rke2-cis-1.24.yaml
Remove `checks` keys with `null` values in the `.spec.compliance.controls` blocks in `ClusterComplianceReport`.
- Close #2167
=> fix: remove null checks values from ClusterComplianceReport in helm chart

docs/getting-started/installation/configuration.md
=> docs: Update configuration.md, added sbom generation flag

deploy/helm/templates/specs/k8s-cis-1.23.yaml
remove
platform: k8s
type: cis
from metadata
fixes #2178
=> chore: platform and type - no metadata values

docs/tutorials/grafana-dashboard.md
This enhancement simplifies the deployment process and ensures that the headless setting is correctly applied from the start when setting up a Dashboard in Grafana .
The trivy-operator Helm chart provides a headless parameter.
```
service:
headless: false    
```
Running the command below to remove the ClusterIP might not work as expected. 
```
kubectl edit service trivy-operator -n trivy-system
```
The workaround for this was to run the following three commands:
```
kubectl get service trivy-operator -o yaml > trivy-operator.yaml
kubectl delete service trivy-operator 
kubectl apply -f trivy-operator.yaml
```
Updated the documentation to reflect this change and removed any references to the previous method
Trivial Fix - Docs Only
=> docs: Grafana Dashboard - Add headless parameter to values.yaml

pkg/plugins/trivy/image.go, pkg/trivyoperator/config.go
Fix the checks for the gcr service account/
This address the pull requested #2108 merged.
- Fixed the typo in const `KeyScanJobUseGCRServiceAccount`.
- Use the DataConfig from the context instead of getting the default which does not contain our value
- Close #2108
=> fix: check gcr service account

build/trivy-operator/Dockerfile, pkg/configauditreport/controller/nodecollector.go, pkg/vulnerabilityreport/controller/scanjob.go
Scan jobs on k8s 1.31 (certainly on EKS at least) fail to be processed leading to no vulnerability reports.
Could it be as simple as this?
- Close #2251
=> fix: vuln scan success criteria met

deploy/helm/README.md, deploy/helm/values.yaml, deploy/static/trivy-operator.yaml
This PR adds `mirror.gcr.io` as a source for `trivy-checks` by default.
=> chore: use mirror.gcr.io for trivy-check by default

deploy/helm/crds/aquasecurity.github.io_clustervulnerabilityreports.yaml, deploy/helm/crds/aquasecurity.github.io_vulnerabilityreports.yaml, deploy/static/trivy-operator.yaml, pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go, pkg/vulnerabilityreport/io.go
This adds package url (pURL) information into the vulnerability report CRD. 
Having the pURL here defines a clear definition of which package this report is actually generated. Also the pURL can be used much better to integrate into other systems.
Since this information is in the trivy scan result anyways it's beneficial to include it in the CR too.
=> feat: add package purl in VulnerabilityReport CRD

.github/workflows/build.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/release.yaml, .goreleaser.yaml, goreleaser-e2e.yaml
This PR bumps up GoReleaser to the latest version (2.4.8):
* change deprecated flags
* add new fields on the config
=> ci: bump up GoReleaser to v2.4.8

.github/workflows/private-registries.yaml
This PR fixes skipped update in #2323
=> ci: bump GoReleaser up for private registry test

CONTRIBUTING.md
Replace `mage  build:all` with `mage build:binary`.
=> docs: Fix mage build command

pkg/plugins/trivy/config.go, pkg/plugins/trivy/image.go, pkg/plugins/trivy/plugin_test.go
The main container with the image command of a scan job fails when pulling the `java-db` from a private registry because of missing credentials. This PR introduces a second init container analogous to the one that downloads the `trivy-db` but downloads the `java-db` if it is to be pulled from a private registry.
This results in the main container not having to download the `java-db` since it is up to date.
=> fix: Missing credentials for downloading the java-db from private registry

pkg/operator/operator.go
=> fix: config insecure when pull policy

pkg/vulnerabilityreport/builder.go, pkg/vulnerabilityreport/builder_test.go
A value generated by `range` is pass-by-value and changes will not apply to original array.
Then I used an index to change the array values directly.
- Close #2240
=> fix: scanjob.customVolumesMount is not applied to the Built-Job

deploy/helm/README.md, deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml
This is a small fix to account for the lack of ability to add extra env vars to the trivy-operator deployment.
This allows specifying eg. AWS IAM session names and other options for eg. secret injection.
- Close #2287 
=> feat: Add extraEnv option to Helm chart

pkg/kube/logs.go
Set Follow=false when retrieving logs from completed job.
Using Follow mode in this case is unnecessary because:
* Follow is used to wait for additional logs that may come from the container
* By the time the operator is collecting the container logs, the container has already completed and will not generate more logs
In cases where the underlying node has resources (fsnotify handle) exhaustion this causes the logs to return an error after the base64 data "failed to create fsnotify watcher: too many open files", and trivy fails to process that scan job due to "illegal base64 data".
I tested this simple change in a cluster that was having the issue, and the operator processed and deleted all the completed scan jobs that were previously being continuously re-processed with base64 failures. …
=> fix: set `follow` to false when retrieving logs

pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go, pkg/plugins/trivy/testdata/fixture/exposedsecret_report.json, pkg/plugins/trivy/testdata/fixture/full_report.json, pkg/plugins/trivy/testdata/fixture/vulnerability_report.json
This PR supersedes #2310, fixes tests and adds safety around the image manifest digest extraction from the report
@afdesk for you review
- Close #2259
=> fix: return the image manifest digest instead of image id

pkg/configauditreport/controller/resource.go, pkg/operator/cluster.go, pkg/operator/predicate/predicate.go, pkg/operator/predicate/predicate_test.go
In a scaled 800-node cluster, running the Trivy operator with KE results in 1600 pods being created for kube-bench. Since kube-bench is an internal Aqua component, its evaluation can be safely skipped. By excluding kube-bench from the Trivy operator's scope, we can reduce the overall memory consumption of the Trivy operator, optimizing its performance in large-scale environments.
=> perf: Exclude kube-bench pods from being evaluated in the Trivy operator

deploy/helm/Chart.yaml
There was a mistake in the previous pipeline (https://github.com/aquasecurity/trivy-operator/actions/runs/13191791193/job/36825958183), so Helm Chart with these versions wasn't published.
This PR hits a github workflow to bump up  the Helm Chart to version 0.26.0 (app version v0.24.0)
=> ci: bump up Helm Chart to version 0.26.0 (app version v0.24.0)

pkg/plugins/trivy/config_test.go, pkg/plugins/trivy/plugin.go, pkg/trivyoperator/config.go
This PR updates default values for config maps.
It allows to run trivy-operator without any additional settings.
=> fix: update default values for configmap

pkg/plugins/trivy/image.go, pkg/plugins/trivy/image_test.go, pkg/plugins/trivy/plugin_test.go, tests/envtest/testdata/fixture/cronjob-expected-scan.yaml, tests/envtest/testdata/fixture/daemonset-expected-scan.yaml, tests/envtest/testdata/fixture/job-expected-scan.yaml, tests/envtest/testdata/fixture/pod-expected-scan.yaml, tests/envtest/testdata/fixture/replicaset-expected-scan.yaml, tests/envtest/testdata/fixture/replicationcontroller-expected-scan.yaml, tests/envtest/testdata/fixture/statefulset-expected-scan.yaml
The trivy command is completed and as it is the main process the entire container is stopped before the stdout buffer is cleared, resulting in malformed output.
This patch has been running for over a month and I have not experienced any lingering scan vulnerability jobs which could not be removed by the operator anymore. Used `kube_job_complete{namespace="trivy-system", condition="true", job_name=~"scan-vulnerabilityreport-[0-9a-f]+"}` to alert for scan jobs with malformed output.
I did refactor the `getCommandAndArgs` function to deduplicate the logic for compressed and not compressed mode, it was essentially the same. Also ensured the options are in alphabetic order.
- Close #1792.
=> fix: sync stdout buffer to file

pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
I've changed behaviour of parseImageRef func.
before:
In case when imageRef -> "my-private-repo.company.com/my-app:some-tag@sha256:1420cefd4b20014b3361951c22593de6e9a2476bbbadd1759464eab5bfc0d34f"
It returns empty tag in Artifact.Tag;
after:
In new version this behaviour fixed and it returns tag instead empty string.
you can see it it "15. private registry image ref tag & with digest" test.
Related issues
Close https://github.com/aquasecurity/trivy-operator/issues/2411
- [Not need] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [Not need] I've added usage information (if the PR introduces new options)
=> fix: parseImageRef tag absence issue when digest in imageRef 

deploy/helm/README.md, deploy/helm/values.yaml
This PR sets a default value for `scanJobAffinity` field as a map.
Prepare
```sh
$ git clone --depth=1 https://github.com/aquasecurity/trivy-operator.git
$ tee ./trivy-operator-values.yaml <<EOF
trivyOperator:
scanJobAffinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: cloud.google.com/gke-spot
operator: In
values:
- "true"
EOF
```
Before:
```sh
$ helm install trivy-operator ./trivy-operator/deploy/helm --namespace trivy-system --create-namespace --values ./trivy-operator-values.yaml
coalesce.go:289: warning: destination for trivy-operator.trivyOperator.scanJobAffinity is a table. Ignoring non-table value ([])
NAME: trivy-operator
LAST DEPLOYED: Tue Mar  4 18:29:21 2025
NAMESPACE: trivy-system
STATUS: deployed
REVISION: 1 …
```
=> fix(helm): use map for `scanJobAffinity` in the Helm Chart

build/trivy-operator/Dockerfile
This PR bump up the base image to version 3.20.6 of Alpine Linux. It's just a minor-update to improve security of trivy-operator docker-image.
This bump from `3.20.3` to `3.20.6` resolving following CVEs in the current docker-image:
`openssl`:
* CVE-2024-9143 (fixed via 3.20.4)
* CVE-2024-13176 (fixed via 3.20.6)
* CVE-2024-12797 (fixed via 3.20.6)
`musl`:
* CVE-2025-26519 (fixed via 3.20.6)
=> chore: bump up base alpine image to 3.20.6

tests/itest/helper/helper.go, tests/itest/trivy-operator/behavior/behavior.go
This PR uses a pre-built vuln image based on `alpine` instead of `nginx` images for integration tests. This image doesn't contain any jar files, so there is no need to download `trivy-java-db`.
it's more stable and improves scan time.
Before:
```
Ran 9 of 9 Specs in 429.834 seconds
FAIL! -- 8 Passed | 1 Failed | 0 Pending | 0 Skipped
Ginkgo ran 1 suite in 10m58.489077216s
Ran 9 of 9 Specs in 128.973 seconds
SUCCESS! -- 9 Passed | 0 Failed | 0 Pending | 0 Skipped
Ginkgo ran 1 suite in 5m59.034072499s
```
After:
```
Build / Run integration tests (pull_request)Successful in 6m
Ran 9 of 9 Specs in 96.032 seconds
SUCCESS! -- 9 Passed | 0 Failed | 0 Pending | 0 Skipped
Ginkgo ran 1 suite in 4m43.909739935s
```
- Close #2460
=> chore(test): update images for integration tests

.github/workflows/build.yaml, magefile.go, tests/itest/helper/helper.go, tests/itest/trivy-operator/behavior/behavior.go
This PR adds pre-downloading test images and upload them into KinD.
Also it uses `wordpress:6.7` instead of `wordpress:5` for Replicaset Integration test.
It allowed to decrease a report size from 24 837 814 to 4 810 124 bytes.
```sh
$ trivy image wordpress:4.9 --format json --image-config-scanners secret --quiet --scanners vuln,secret --skip-db-update --slow --list-all-pkgs -o result_wordpress-4.9.json
$ ls -l
-rw-r--r--@ 1 amf  staff   5567245 Mar 25 19:38 result_wordpress-4.9.json
```
Before:
```sh
$ trivy image wordpress:5 --format json --image-config-scanners secret --quiet --scanners vuln,secret --skip-db-update --slow --list-all-pkgs -o result_wordpress.json
$ ls -l
-rw-r--r--@ 1 amf  staff  24837814 Mar 25 18:56 result_wordpress.json
```
After:
```sh
$ trivy image wordpress:6.7 …
```
=> test: improve integration tests

go.mod, go.sum
Let's keep the AquaSec Trivy-Operator dependency `golang.org/x/oauth2` up-to-date. The current latest Docker-Image tag `0.25.0` using an older version of oauth2 which could be affected by https://github.com/golang/go/issues/71490 (https://nvd.nist.gov/vuln/detail/CVE-2025-22868). So, let's upgrade oauth2 from `0.25.0` to `0.27.0` for AquaSec Trivy-Operator.
Having this said, I ran:
```
go get golang.org/x/oauth2@v0.27.0
go mod tidy
```
Basically, this dependency update just aim to silence some (SBOM-based) scanners, while checking `aquasec/trivy-operator:0.25.0` Docker-Image.
I didn't create a linked issue here in the repo yet - If this would be better/required to have an issue, I'm happy to create one and link this here with Close/Fixed reference.
=> chore(deps): bump golang.org/x/oauth2 from 0.25.0 to 0.27.0 - resolve CVE-2025-22868

pkg/plugins/trivy/image.go
trivy-operator does not check excluded images in client server mode.
This change fixes this behavior.
I verified the fixed behavior in a real setup, where excludes where not taken into account previously.
Note: The feature was previously introduced in https://github.com/aquasecurity/trivy-operator/pull/2080.
=> fix: skip excluded images in client server mode

pkg/configauditreport/controller/helper.go, pkg/operator/operator.go, pkg/policy/hash_bench_test.go, pkg/policy/policy.go, pkg/policy/policy_test.go
This PR introduces the following improvements:
* Caching for Computed Hash Values: Adds a caching mechanism to store computed values for each Kubernetes resource type. This improves performance by avoiding redundant calculations.
* Correct Cache Size for Downloaded Policies: Sets an appropriate cache size limit for storing downloaded policies.
Benchmark Results:
```go
% go test -bench=. -benchtime=10s -count=3
goos: darwin
goarch: arm64
pkg: github.com/aquasecurity/trivy-operator/pkg/policy
cpu: Apple M3 Max
BenchmarkPolicies_Hash-14                                       29993532               378.2 ns/op            81 B/op          5 allocs/op
BenchmarkPolicies_Hash-14                                       29637028               377.1 ns/op            81 B/op          5 allocs/op …
```
=> chore: improve cache for policies

.github/workflows/release.yaml
Frees up space to avoid issues such as https://github.com/aquasecurity/trivy-operator/actions/runs/14788590999/job/41521687003 where no disk space is left on device.
=> chore(ci): Free up space to build

pkg/configauditreport/controller/helper.go, pkg/configauditreport/controller/helper_test.go, pkg/configauditreport/controller/resource.go, pkg/policy/policy.go
In some cases, a check result may not contain a message — more details can be found here: https://github.com/aquasecurity/trivy-operator/issues/1742 (fixed https://github.com/aquasecurity/trivy-operator/pull/1845).
Previously, messages were also missing for all successfully passed checks, and those were being skipped as well.
This PR changes that behavior to ensure successful checks are no longer skipped even if they lack a message.
- Close #2527
=> fix(policy): show passed checks

deploy/helm/README.md, deploy/helm/values.yaml
Remove comment for `trivy.existingSecret` and change the default to `false` for backwards compatibility.
Since the value is now present in the values.yaml it is also generated into the README.md.
- Close #2282
=> docs(helm): Add trivy.existingSecret to README

docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md
This small PR updates the `Trivy fs command` source guide to point to:
```markdown
https://aquasecurity.github.io/trivy-operator/latest/docs/design/design_trivy_file_system_scanner/
```
Relevant page: https://aquasecurity.github.io/trivy-operator/latest/docs/design/design_vuln_scan_job_in_same_namespace_of_workload/
- Close #XXX
=> docs: update trivy fs source

.golangci.yml, magefile.go, pkg/kube/object.go
Update golangci-lint to 2.1.6 and clean up config
- #2540
- #2558
=> chore(deps): bump golangci-lint to v2.1.6

deploy/helm/README.md, deploy/helm/values.yaml, pkg/plugins/trivy/config.go, pkg/plugins/trivy/config_test.go, pkg/plugins/trivy/image.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
This PR adds support of [Trivy config file](https://trivy.dev/latest/docs/references/configuration/config-file/#registry-options). it needs because Trivy allows set up mirrors for remote container and databases only via Trivy config file.
```sh
config="registry:
mirrors:
index.docker.io:
- mirror.gcr.io"
kubectl patch cm trivy-operator-trivy-config -n trivy-system \
--type merge \
-p "$(jq -n --arg config "$config" '{"data": {"trivy.configFile": $config}}')"
```
- Close #2274
=> feat: add using Trivy config files

pkg/operator/operator.go
Remove the artifact construction during operator startup, to allow a new artifact to be created with up to date registry credentials during policy refresh
Tested on a live AKS cluster with no `401 Unauthorized` errors and verified policy bundle refresh:
```
$ kubectl exec -it trivy-operator-... -n trivy-operator -- /bin/sh
/ $ cat /tmp/policy/metadata.json
{"Digest":"sha256:e13d31ec41e7a61a0eeb42afccd73a8e2802244c5c772764a5e2ffb30cab727c","DownloadedAt":"2025-05-25T16:39:15.852887038Z"}
/ $ cat /tmp/policy/metadata.json
{"Digest":"sha256:e13d31ec41e7a61a0eeb42afccd73a8e2802244c5c772764a5e2ffb30cab727c","DownloadedAt":"2025-05-26T16:39:17.508803701Z"}
```
https://github.com/aquasecurity/trivy-operator/issues/2565
=> fix(policy): remove oci artifact construction at startup

.golangci.yml, pkg/compliance/io.go, pkg/compliance/io_test.go, pkg/configauditreport/io_test.go, pkg/exposedsecretreport/io_test.go, pkg/infraassessment/io_test.go, pkg/kube/object_test.go, pkg/kube/secrets_test.go, pkg/operator/cluster.go, pkg/operator/operator.go, pkg/operator/ttl_report.go, pkg/operator/ttl_report_test.go, pkg/plugins/trivy/config.go, pkg/plugins/trivy/config_test.go, pkg/policy/loader.go, pkg/policy/policy_test.go, pkg/rbacassessment/io_test.go, pkg/sbomreport/io_test.go, pkg/trivyoperator/config_test.go, pkg/vulnerabilityreport/controller/trivyserver_test.go, pkg/vulnerabilityreport/io_test.go, pkg/webhook/webhookreporter_test.go, tests/itest/helper/helper.go, tests/itest/trivy-operator/behavior/behavior.go
Enable and fixes contextcheck and usetesting linters, this helpshandling contexts in running code as in testing.
Also use revive to be sur that the contexts are used while being provided as function arguments
=> fix: enable contextcheck and usetesting linters

.golangci.yml, pkg/compliance/clustercompliancereport.go, pkg/compliance/io.go, pkg/configauditreport/builder.go, pkg/configauditreport/controller/nodecollector.go, pkg/configauditreport/controller/resource.go, pkg/configauditreport/io.go, pkg/infraassessment/builder.go, pkg/infraassessment/io.go, pkg/kube/object.go, pkg/operator/cluster.go, pkg/operator/predicate/predicate.go, pkg/rbacassessment/builder.go, pkg/rbacassessment/io.go, pkg/sbomreport/io.go, pkg/vulnerabilityreport/controller/scanjob.go
This enables the following revive rules:
* [duplicated-imports](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#duplicated-imports)
* [early-return](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#early-return)
* [if-return](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#if-return)
* [indent-error-flow](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#indent-error-flow)
* [superfluous-else](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#superfluous-else)
* [use-any](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#use-any)
* [use-errors-new](https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#use-errors-new)
* …
=> fix: enable more revive rules

.github/workflows/build.yaml, .github/workflows/chart-testing.yaml, .github/workflows/private-registries.yaml, .github/workflows/publish-helm-chart.yaml, .github/workflows/release.yaml
This PR bumps up KinD to the latest version and also fixes a warning about using `@sha256`:
```
Please include the @sha256: image digest from the image in the release notes. You can find available image tags on the release page, https://github.com/kubernetes-sigs/kind/releases/tag/v0.24.0
```
=> ci: bump up KinD to the latest version - v0.29.0

.golangci.yml, pkg/compliance/clustercompliancereport.go, pkg/compliance/io.go, pkg/configauditreport/controller/nodecollector.go, pkg/configauditreport/controller/resource.go, pkg/infraassessment/builder.go, pkg/operator/cluster.go, pkg/plugins/trivy/jobspec.go, pkg/policy/policy.go, pkg/rbacassessment/builder.go, pkg/vulnerabilityreport/controller/scanjob.go
This enables the following go-critic rules:
* [indexAlloc](https://go-critic.com/overview.html#indexalloc)
* [octalLiteral](https://go-critic.com/overview.html#octalliteral)
* [regexpSimplify](https://go-critic.com/overview.html#regexpsimplify)
* [sloppyReassign](https://go-critic.com/overview.html#sloppyreassign)
=> fix: enable more go-critic rules

pkg/plugins/trivy/image.go, pkg/plugins/trivy/jobspec.go, pkg/plugins/trivy/plugin.go, pkg/plugins/trivy/plugin_test.go
This PR updates the authorization method for accessing the private repository containing JavaDB.
The initContainer no longer downloads the JavaDB database. Instead, it now performs authentication against the private registry.
This change eliminates unnecessary downloads of the heavy JavaDB image in scenarios where it is not needed, improving efficiency and reducing overhead.
It fixes next similar bugs for `ClientServer` modes, which were updated for `Standalone`:
- #2353
- #2073 
- Close #2510 
- Close #1836
=> fix: login private registry instead of download JavaDB

.github/workflows/chart-testing.yaml, .github/workflows/private-registries.yaml
This PR uses kind action instead of install kind script for github workflows.
=> ci: use kind action instead of install kind script

.github/workflows/private-registries.yaml, pkg/plugins/trivy/image.go, pkg/plugins/trivy/image_test.go, pkg/plugins/trivy/plugin_test.go, tests/envtest/testdata/fixture/cronjob-expected-scan.yaml, tests/envtest/testdata/fixture/daemonset-expected-scan.yaml, tests/envtest/testdata/fixture/job-expected-scan.yaml, tests/envtest/testdata/fixture/pod-expected-scan.yaml, tests/envtest/testdata/fixture/replicaset-expected-scan.yaml, tests/envtest/testdata/fixture/replicationcontroller-expected-scan.yaml, tests/envtest/testdata/fixture/statefulset-expected-scan.yaml
This PR uses `--output` flag for save JSON reports, instead of output redirection to a file. So we don't need `sync` command anymore (it was added #2191).
Also it adds a log keeping on scanning pods: Trivy prints logs in `stderr`, so we can redirect this output into a file:
```sh
... 2>/tmp/scan/%s.log
```
- Close #2290
- Close #2552
=> chore: show log on scan jobs

build/trivy-operator/Dockerfile.ubi9
This PR bumps up UBI to the latest version 9.6-1750782676 - https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5?container-tabs=gti&gti-tabs=unauthenticated
```sh
$ mage build:dockerUbi9
$  trivy i docker.io/aquasecurity/trivy-operator:dev-ubi9 --cache-backend memory
```
Before:
```sh
Report Summary
┌─────────────────────────────────────────────────────────────┬──────────┬─────────────────┬─────────┐
│                           Target                            │   Type   │ Vulnerabilities │ Secrets │
├─────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ docker.io/aquasecurity/trivy-operator:dev-ubi9 (redhat 9.6) │  redhat  │       57        │    -    │ …
```
=> chore: update UBI to version 9.6-1750782676

pkg/trivyoperator/config.go
This PR sets a correct default value for a node-collector repo.
=> chore: use a correct default repo for node-collector

.github/workflows/build.yaml
Fixes an error where multiple commands were joined into one, causing `kubectl` to misinterpret flags.
```bash
Run kubectl logs -n trivy-system deployment/trivy-operator echo "reports:" kubectl get clustervulnerabilityreports.aquasecurity.github.io -A
kubectl logs -n trivy-system deployment/trivy-operator echo "reports:" kubectl get clustervulnerabilityreports.aquasecurity.github.io -A
shell: /usr/bin/bash -e {0}
env:
KIND_VERSION: v0.[2](https://github.com/aquasecurity/trivy-operator/actions/runs/16005323687/job/45151546248?pr=2631#step:20:2)9.0
KIND_IMAGE: kindest/node:v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f
DOCKER_CLI_EXPERIMENTAL: enabled
error: unknown shorthand flag: 'A' in -A
See 'kubectl logs --help' for usage.
```
- …
=> fix(ci): use multiline syntax to print logs on failure

RELEASING.md
This PR fixes a typo in the `RELEASING.md` documentation by updating the Helm chart file name from `nsa-1.0.yaml` to `k8s-nsa-1.0.yaml`
=> docs: fix typo in RELEASING.md for Helm chart file name

.github/workflows/release-snapshot.yaml
This pull request adds a new step to the release snapshot workflow to enhance security by scanning an additional image for vulnerabilities.
Workflow enhancements:
* [`.github/workflows/release-snapshot.yaml`](diffhunk://#diff-237e89a82f696b00a56feb5feabd760fa7ff2baf5c7678b7b86a47364e8e6605R51-R56): Added a step to scan the `mirror.gcr.io/aquasec/trivy-operator:${{ github.sha }}-ubi9-amd64` image for vulnerabilities using the `aquasecurity/trivy-action` GitHub Action.
=> ci: add ubi images for vuln pre-release scanning

goreleaser-e2e.yaml
fix: add ubi9 images for nightly testing
=> fix: add ubi9 images for nightly testing

build/trivy-operator/Dockerfile.ubi9
This PR bumps up UBI9 version to 9.6-1752587672.
Before:
```sh
trivy i --cache-backend=memory --ignore-unfixed docker.io/aquasecurity/trivy-operator:dev-ubi9 -q
Report Summary
┌─────────────────────────────────────────────────────────────┬──────────┬─────────────────┬─────────┐
│                           Target                            │   Type   │ Vulnerabilities │ Secrets │
├─────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ docker.io/aquasecurity/trivy-operator:dev-ubi9 (redhat 9.6) │  redhat  │        2        │    -    │
├─────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ usr/local/bin/trivy-operator                                │ gobinary │        0        │    -    │ …
```
=> chore: bump up UBI 9 version to 9.6-1752587672

go.mod, go.sum
=> chore: bump up docker for CVE-2025-54388

go.mod
This PR bumps up Go version to 1.24.6 to fix CVE-2025-47907.
Before:
```sh
trivy i docker.io/aquasecurity/trivy-operator:dev -q --cache-backend memory
Report Summary
┌───────────────────────────────────────────────────────────┬──────────┬─────────────────┬─────────┐
│                          Target                           │   Type   │ Vulnerabilities │ Secrets │
├───────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ docker.io/aquasecurity/trivy-operator:dev (alpine 3.22.1) │  alpine  │        0        │    -    │
├───────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ usr/local/bin/trivy-operator                              │ gobinary │        1        │    -    │ …
```
=> chore: bump up Go to version 1.24.6

pkg/vulnerabilityreport/controller/scanjob.go, pkg/vulnerabilityreport/controller/scanjob_test.go
```
New
Performance: ~277ms/op
Memory: 155KB/op
Allocations: 27 allocs/op
Old
Performance: ~371ms/op
Memory: 75KB/op
Allocations: 9 allocs/op
```
- https://github.com/aquasecurity/trivy-operator/discussions/2674
=> perf: optimize report processing

deploy/helm/templates/monitor/servicemonitor.yaml, deploy/helm/values.yaml
The ServiceMonitor resource is not always created due to the check for the `"monitoring.coreos.com/v1"` API. This is due to the helm's `.Capabilities` object not always being present depending on the method of deployment chosen (eg. `helm template`, using `kustomize`, using ArgoCD).
This change removes the check from the template so that the `ServiceMonitor` resource will always be created if the ServiceMonitor is enabled.
Before:
```
$ helm template deploy/helm/ --set serviceMonitor.enabled=true | yq 'select(.kind == "ServiceMonitor")'
$ 
```
After:
```
$ helm template deploy/helm/ --set serviceMonitor.enabled=true | yq 'select(.kind == "ServiceMonitor")'
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
name: release-name-trivy-operator
namespace: default
labels: …
```
=> fix(helm): always attempt to create ServiceMonitor when it is enabled
